SUseDefaults = ' Benutze Vorgaben für: ';
SForeground = 'V&ordergrund';
SBackground = 'Hinter&grund';
SProperties = 'Eigenschaften';

SOkButton = 'Ok';
SCancelButton = 'Abbruch';
SHelpButton = '&Hilfe';
//=================== UNTRANSLATED SECTION ===================
{------------ This section will be translated ---------------}
sDCCloseButton = 'Close';
sDCResumeButton = 'Resume';
//================= END UNTRANSLATED SECTION =================
SSaveButton = 'Speichern';
SDeleteButton = 'Löschen';

SKBDVisualStudio = 'Visual Studio';
SExportToTitle = 'Exportiere nach';
SInspectOptions = 'Inspektor';
SDesignerOptions = 'Designer';
SEditorColor = 'Edit&orfarbe:';
SColor2 = 'F&arbe:';
SStyle2 = 'St&il:';
SOptionWidth2 = 'B&reite:';
SVisible2 = 'Si&chtbar';
SFileExportToMenu = '&Exportiere nach';
SUseReadOnlyColor = 'Use &Read-Only Color';
SReadOnlyColor = 'Read-&Only Color:';
SUseSpecSymbs = 'Draw &Special Symbols';
SEOF = 'EOF:';
SEOL = 'EOL:';
SSpace = 'Space:';
STab = 'Tab:';

//Die "&" in den Texten zeigen, welcher Buchstabe unterstrichen wird, also
//per Alt + "Buchstabe" die Anwahl des Menüs möglich ist.

SKBDClassic = 'Klassisch';
SKBDBrief = 'Brief';
SKBDEpsilon = 'Epsilon';

STSDefaults = 'Vorgaben';
STSClassic = 'Klassisch';
STSOcean = 'Ozean';
STSTwilight = 'Zwielicht';

SVerbActionListEditor = 'ActionListen Editor...';
// ActionList => Bezeichnung einer Komponente, übersetzung würde irritieren
SVerbStandardAction = 'Neue Standard Aktion...';


//dcRenPropPageUnit
SDCRenPropPageFormCaption = 'Seite umbenennen';
SDCAddPropPageFormCaption = 'Seite hinzufügen';
SDCPageNameCaption = 'Seitenname:';
SDCDublicatePageName = 'Der Name '#39'%s'#39' wird bereits benutzt.';

//dcPalettePropUnit
SDCPalettePropFormCaption = 'Palette';
SDCPaletteSheetCaption = 'Palette';
SDCAddBtnCaption = '&Hinzufügen...';
SDCDeleteBtnCaption = '&Löschen';
SDCRenameBtnCaption = 'Umbe&nennen...';
SDCMoveUpBtnCaption = 'Nach &Oben';
SDCMoveDownBtnCaption = 'Nach &Unten';
SDCPagesLabelCaption = 'Seiten:';
SDCComponentLabelCaption = 'Komponenten:';
SDCAllCompItemCaption = '[Alle]';
SDCDefaultPagesBtnCaption = '&Standardseiten';

SDCNameColCaption = 'Name';
SDCPackageColCaption = 'Package';
SDCPageColCaption = 'Seite';

SDCFullPageError = 'Eine Seite muß leer sein bevor sie gelöscht werden kann.';
sDCHiddenComponent = '[Versteckt]';
sDCShowBtnCaption = '&Zeige';
sDCHideBtnCaption = '&Verstecke';


// ------------------- New Object captions -----------------

SErrAlreadyInNewDialog = '%s ist für den neuen Dialog schon registriert';

SDelphiApp = 'Delphi Anwendung'; // Application => Anwendung
SVBScriptApp = 'VBScript Anwendung';
SJScriptApp = 'JScript Anwendung';
SPerlApp = 'Perl Anwendung';
SPythonApp = 'Python Anwendung';

SDelphiForm = 'Delphi Formular'; // Form => Formular
SVBScriptForm = 'VBScript Formular';
SJScriptForm = 'JScript Formular';
SPerlForm = 'Perl Formular';
SPythonForm = 'Python Formular';

SDelphiDataModule = 'Delphi Daten Module'; //Daten Modul
SVBScriptDataModule = 'VBScript Daten Modul';
SJScriptDataModule = 'JScript Daten Modul';
SPerlDataModule = 'Perl Daten Modul';
SPythonDataModule = 'Python Daten Modul';

STextFile = 'Text Datei';
SHTMLtext = 'HTML Datei';
SSqltext = 'SQL Datei';

SDelphiUnit = 'Delphi Unit'; //Unit
SJScriptUnit = 'JScript Unit';
SVBScriptUnit = 'VBScript Unit';
SPerlUnit = 'Perl Unit';
SPythonUnit = 'Python Unit';

SDelphiReport = 'Delphi Bericht'; // Bericht
SPerlReport = 'Perl Bericht';
SVBScriptReport = 'VBScript Bericht';
SJScriptReport = 'JScript Bericht';
SPythonReport = 'Python Bericht';
SSimpleReport = 'Einfacher Bericht';

SSimpleForm = 'Einfaches Formular';
SSimpleDataModule = 'Einfaches Datenmodul';

SProjectFile = 'Projektdatei';
SWorkSpaceFile = 'WorkSpace-Datei'; //workspace ??

//--------------------- File Types captions --------------

SAllFiles = 'Alle Dateien';
SUnitFiles = 'Unit Dateien';
//=================== UNTRANSLATED SECTION ===================
{------------ This section will be translated ---------------}
sDelphiFiles = 'Delphi units';
sInterfaceFiles = 'Interface files';
sTextFiles = 'Text files';
//================= END UNTRANSLATED SECTION =================
SProjectWorkSpace = 'Projekt/WorkSpace'; //workspace ??
SFormFile = 'Formulardatei';

//--------------------- Verb captions --------------

// !!! Das "&"
SVerbMenuItems = 'Editiere &Elemente...';
SVerbSave = '&Speichern';
SVerbSaveAs = 'Speichern &als...';
SVerbClose = '&Schließen';
SVerbActivateProject = 'Aktiviere Projekt';
SVerbAdd = '&Hinzufügen...';
SVerbSQLEditor = 'SQL Editor...';
SVerbResourceMaster = 'Resource Master';
SVerbIdeInspector = 'IDE Inspektor';
SVerbMultiSourceEditor = 'Quellen editieren...';

SRegPackages = 'Pakete';

//--------------------- Convert Errors ---------------------------
SErrInvalidBoolean = '''%s'' ist kein gültiger boolescher Wert';

//--------------------- Parser Errors ----------------------------

SErrCharPos = ' in Reihe:%d, Buchstabe:%d. ';
SErrMaxIfDefReached = 'Nur %d verschachtelte Ebenen von Compilerbefehlen sind möglich';
SErrCompilerDirective = 'Ungültiger Compilerbefehl: "%s"';
STokenListEmpty = 'Zeichenliste ist leer';
SErrFutureState = 'Status liegt in der Zukunft'; // Status ist in der Zukunft??
SErrTokenExpected = 'Zeichen %d wird erwarted';

// -------------------- Other Errors -------------------------

SErrFormNameEmpty = 'Formularname kann nicht leer sein';
SErrMethodReferenced = 'Referenzmethode %s existiert nicht. Referenz entfernen?';
SErrControlsInData = 'Controls können nicht zu Daten Modulen hinzugefügt werden'; //controls??
SErrInvalidModuleClass = 'Ungültige Modul Klasse - %s';
SErrCreatingForm = 'Fehler beim Erstellen des Formulars';
SErrUpdateRes = 'Fehler beim Ändern der Resource';
SErrOnlyForms = 'Diese Version von Resource Master kann nur Formulare editieren';
SErrAlreadyInProject = 'Objekt mit dem Namen "%s" gibt es bereits im Projekt';
SErrOnlyWin32FileSystem = 'Diese Operation kann nur im Win32 Dateisystem ausgeführt werden';
SErrObjectNotInProject = 'Objekt %S gibt es im aktiven Projekt nicht';
SErrNotInstantReport = 'kann nur in Instant Report eingefügt werden'; //instant??
SErrAlreadyUseAll = 'Objekt %S benutzt bereits alle verfügbaren Objekte';
SErrBadPropStream = 'Fehler in Eigenschaften stream'; //stream??
SErrNoComp = 'Komponente %s existiert nicht';
SErrAlreadyHaveOwner = 'Dieser Workspace hat bereits einen Besitzer'; //Workspace??
SErrNonMonoSpacedFont = 'Nur Nicht-Proportionale Schriftarten können benutzt werden';
SerrInvalidMoving = 'Kann nicht hierhin bewegen';
sErrCantOpen = 'Kann Modul %s'#13#10' nicht öffnen Fehlercode : %d';
SErrNoNewExtensions = 'Neue Erweiterungen sind nicht installiert';
SErrOpenFile = 'Fehler beim Öffnen von %s';
SErrorCreateMap = 'Error creating file mapping'; //file mapping ??
SErrorMap = 'Can''t map %s into memory'; // ??
SErrReadOnlyFile = '''%s'' ist schreibgeschützt';

//------------------Scripter constants ----------------------------------

SErrScriptEngineRun = 'Die Scriptingengine ließ sich nicht starten';
SErrAlreadyLaunched = 'Das Programm läuft bereits';
SErrNoCodeDesigner = 'Es ist kein Codedesigner für %s Dateityp registriert';
SErrNoScriptRunner = 'Für Dateityp % s ist kein Script Runner registriert';
SErrNoScriptForLang = 'Für Sprache %s ist kein Script Runner registriert';
SErrUnitNotFound = 'Kann Unit %s nicht laden';
SErrNoRunnableObjects = 'Kann nicht ausführen';
SErrExternalRun = 'Fehler beim Ausführen des Programms : %s';
SContinueExecution = 'Ausführung fortsetzen?';
SFilePrefix = 'Datei : ';
//----------------------------------------------------

SOtherGroupName = 'Andere'; // in Objekt Inspektor
STitleFilterName = 'Filter Name';
STitleFilter = 'Filter';
SVerbUsesRetriever = 'Benutzt Retriever...';
SVerbAssignVerbs = 'Verben zuordnen';
SCapUseObjects = 'Benutze Objekte in ';
SCapRunParameters = 'Startparameter';

SPageNew = 'Neu';
SPageForm = 'Formular';
SPageUnit = 'Unit';
SPageReport = 'Bericht';
SPageDataModule = 'Datenmodul';

SWorkSpace = 'WorkSpace';
SProject = 'Projekt';

SErrCantSaveObject = 'Kann Objekt nicht speichern';

SErrDeleteFile = 'Kann Datei %S nicht löschen';
SErrRenameFile = 'Kann Datei %s nicht in %s umbenennen';
SErrCantCreateTemp = 'Kann keinen vorläufigen Dateinamen erzeugen';

SStatModified = 'Verändert';
SStatInsert = 'Einfügen';
SStatOverwrite = 'Überschreiben';
SStatReadOnly = 'Schreibgeschützt';

SErrOpenForm = 'Fehler beim öffnen des Formulars';
SErrReadProps = 'Fehler beim Lesen der Eigenschaften';
SErrDuplicateItem = 'Kann doppeltes Element nicht einfügen'; // Item??

SClipboard = 'Zwischenablage';

// OCX
SErrOCXLoadFail = 'Laden von "%s" gescheitert';
SErrOCXCantFindProc = '%s Prozedur nicht gefunden in "%s"';
SErrOCXRegFail = 'Aufruf von %s scheiterte in "%s"';

// ----------------- Filters ------------------------
SOCXFilter = 'ActiveX (*.ocx)|*.ocx';
SAVIFilesFilter = 'AVI Dateien (*.avi)|*.avi';
{$IFDEF CPB3}
SPackagesFilter = 'Pakete (*.bpl)|*.bpl';
{$ELSE}
SPackagesFilter = 'Pakete (*.dpl)|*.dpl';
{$ENDIF}
SPictFilter = 'Alle (*.jpg;*.jpeg;*.bmp;*.ico;*.emf;*.wmf)' +
'|*.jpg;*.jpeg;*.bmp;*.ico;*.emf;*.wmf|JPEG Image File (*.jpg;*.jpeg)|*.jpg;*.jpeg|' +
'|Bitmaps (*.bmp)|*.bmp|Icons (*.ico)|*.ico|' +
'Enhanced Metafiles (*.emf)|*.emf|Metafiles (*.wmf)|*.wmf';
SFormFilter = 'Delphi Formular|*.dfm';
SColorStyleFilter = 'Farbschema (*.rgb)|*.RGB';

SExeFilter = 'Ausführbare Dateien|*.EXE;*.DLL;*.DPL;*.BPL|Alle Dateien|*.*';

SExecutableFiles = 'Ausführbare Dateien';

// ---------------- Palette Pages ---------------------

SPalStandard = 'Standard';
SPalAdditional = 'Weitere';
SPalWin32 = 'Win32';
SPalDialogs = 'Dialoge';
SPalSystem = 'System';
SPalDataControls = 'Datensteuerung'; // Data controls??
SPalDataAccess = 'Datenzugriff';
SPalMidas = 'Midas';
SPalWin31 = 'Win 3.1';
SPalActiveX = 'ActiveX';
SPalDecisionCube = 'Decision Cube';
SPalQReport = 'QReport';

// ------------------- Form captions ------------------

SCapLines = ' Zeilen)';
SCapGotoLineNumber = 'Gehe zu Zeilennummer';
SCapEnterNewLine = 'G&eben Sie die neue Zeilennumer ein:';
SCreateOrderCaption = 'Erzeugungsreihenfolge';
STabOrderCaption = 'Tabreihenfolge';
SCapEditing = 'Editing '; // bearbeitend??
SCapWindowList = 'Fensterliste';
SCapAddFields = 'Felder einfügen';
SCapSelectSource = 'Wählen Sie die Datenquelle';
SCapScale = 'Skalieren';
SCapScalingFactor = '&Skalierungsfaktor:';
SCapProjectManager = 'Projektverwaltung';
SErrDlg = 'Fehler beim Lesen des Formulars';
SFindText = 'Text finden';
SReplText = 'Text ersetzen';
SPstoredEdit = 'Property Storage Editor'; //??
SPackActiveX = 'Pakete/ActiveX';
SNewItem = 'Neues Element';
SNewField = 'Neues Feld';
SFilterEdit = 'Filtereditor';
SObjectExplorer = 'Objektexplorer';
SStrlEdit = 'Stringlisteneditor';

// ------------------- dcl0.pas ----------------------------

SSaveChanges = 'Änderungen an %s speichern?';
SCantUseMore = 'Diese Unit benutzt bereits alle verfügbaren Units';
SUseUnitCaption = 'Benutze Unit';

SEmptyFileName = 'Dateiname kann nicht leer sein';
SNotValidIdent = '''%s'' ist kein gültiger Name.';
SOpenFileExt = 'Delphi Unit|*.pas|Delphi Formular|*.dfm';
SOnlyOneInstant = 'Es kann nur eine Instanz von TInstantReport erzeugt werden';

// ------------------- dcfdes.pas------------------------
SAligntoGrid = 'Am &Raster ausrichten';
SBringToFront = 'Nach &Vorne bringen';
SSendToBack = 'Nach &Hinten bringen';
SDesAlign = '&Ausrichten...';
SDesSize = '&Grö&sse...';
SDesScale = 'skali&eren...';
SDesTabOrder = '&Tabulatorreihenfolge...';
SDesCreationOrder = '&Erzeugungsreihenfolge...';

// ----------------- dcstring.pas ----------------------

SVerbProperties = 'Eigenschaften...';
SInvalidTabRack = 'Ungültige Karteireiterlasche';
SReadOnlyStream = 'Kann nicht in einen schreibgeschützten Stream schreiben'; //stream
SErrBlankSearch = 'Der Suchbegriff darf nicht leer sein';
SErrEmptySel = 'Versuchte, markierten Block zu durchsuchen, aber er war fehlerhaft';
SErrOutsideSel = 'Versuchte, markierten Block ab dem Curser zu durchsuchen, aber der Curser ist außerhalb des Blocks';
SErrNotFound = 'Suchbegriff ''%s'' wurde nicht gefunden';
SAskReplace = 'Dieses Auftreten von ''%s'' ersetzen?';
SAskSaveFile = ' Änderungen als %s speichern?';

// ----------------------- dcgen.pas ------------------------------

SErrStackEmpty = 'Stapelspeicher ist leer';
SErrPackloaderExists = 'Paketlader existiert bereits in der Anwendung';
SErrUnknRegType = 'Dieser Typ wird nicht durch WriteToRegistry unterstützt';

// ---------------------- dcpload.pas --------------

SErrWithoutPackages = 'Paketlader wird nicht funktionieren wenn die Anwendung ohne Pakete kompiliert wurde';
SErrorPackageLoad = 'Fehler während des Ladens von Paket %S ';
SOnlyOnePackageLoader = 'Es kann nur eine Instanz von TDCPackageLoader erzeugt werden';
SUnkPackageHandle = 'Unbekannter Paket-handler';
SPackAlrregist = 'Kann Paket %s'#13#10' nicht installieren weil Paket %s den gleichen Basisnamen hat';

// ---------------------- dcl2.pas --------------

SErrFileNotFound = 'Datei %S nicht gefunden';

// ---------------------- reswrite.pas --------------

SError = #13#10'Fehler code : %d';
SErrFileOpen = 'kann Datei nicht zum Schreiben öffnen';
SErrMap = 'Can''t map file'; //map-Abbilden??
SErrMapView = 'Kann MapViewOfFile nicht ausführen';
SErrEXE = 'Falsches Dateiformat';
SErrNoResources = 'Diese Datei enthält keine Resourcen'; //resources??
SErrResNotFound = 'Resource nicht gefunden';

// ---------------------- dcdbreg.pas --------------

SLoadDefault = 'Standardparameter laden?';
SErrNoAliasOrDriver = 'AliasName oder DriverName Eigenschaft sollte angegeben werden';
SVerbLoadDefault = 'Lade &Standardparameter...';
SVerbExecute = 'A&usführen';
SVerbColumnsEditor = 'Spa&lteneditor...';

// ---------------------- ctrlreg.pas --------------

SVerbEditPropList = '&Eigenschaftenliste bearbeiten...';
SVerbPropOrder = '&Properties Reihenfolge...'; //??Reihenfolge der Eigenschaften?
SVerbInsertObject = 'Objekt einfügen...';
SVerbObjectProperties = 'Objekteigenschaften...';
SVerbObjectSettings = 'Objekteinstellungen...';
SVerbNextFrame = '&Nächster Rahmen';
SVerbPreviousFrame = '&Vorheriger Rahmen';
SVerbNewPage = 'Neue Seite';
SVerbNextPage = 'Nächste Seite';
SVerbPreviousPage = 'Vorherige Seite';
SVerbNewButton = 'Neuer &Schalter';
SVerbNewSeparator = 'Neuer &Trenner';

SVerbInputMaskEditor = 'E&Ingabemasken Editor...';
SVerbMaskedTextEditor = '&MaskierterText Editor...';
SVerbImageEditor = 'B&ild bearbeiten..';
SVerbSectionsEditor = 'Sektio&nen-Editor...';
SVerbPanelsEditor = '&Panels-Editor...';
SVerbItemsEditor = '&Items-Editor...';
SVerbLinesEditor = '&Linien-Editor...';
SVerbTabsEditor = '&Tabreihenfolge-Editor...';
SVerbMenuDesigner = 'Menu-Designer...';
SVerbBandsEditor = 'Ban&den-Editor...';
SVerbObjectInspector = 'Objektinspektor';

SErrNotImplemented = 'Nicht implementiert';

// ---------------------- dcmemo.pas --------------

SLoadColorStyles = 'Farbschema laden';
SSaveColorStyles = 'Farbschema speichern';
SErrNotRGBFile = 'Keine Farbschema Datei';
sScrollLine = '~Line~';
// ---------------------- dcedit.pas --------------

sErrSelfLink = 'Kann nicht auf sich selbst verweisen';
sErrEmptyPopupClass = 'PopupWindowClass ist nicht festgelegt';
SSelectDirectory = 'Verzeichniss wählen';

// ---------------------- dcmenu.pas --------------

sErrMultipleInstance = 'Es kann nur eine Instanz von DCMenu im Formular plaziert werden.';
sErrInfoAlreadySet = 'Information für diesen Eintrag wurde bereits eingegeben.';
sErrMainMenuImage = 'Hauptmenüeinträge können kein Bild enthalten';

// ---------------------- dcsplit.pas ---------------

SVerbSetMinSize = 'MinSize Eigenschaft festlegen';

// ---------------------- dctree.pas ---------------
SConfirmDelete = 'Einträge löschen?'; // item??

// ---------------------- dcdbtree.pas ---------------

sDatasetName = '*.cds';
sAddFields = '&Felder hinzufügen...';
sAddAllColumns = '&Alle Spalten hinzufügen';
sLoadDefValues = 'Vorgaben wiederherstellen?';
sFieldEditor = '&Felder Editor...';
sParamEditor = '&Parameter Editor...'; //params=parameter??
serrNameAlredyExists = 'Ein Feld mit dem Namen %s existiert bereits';
SReplaceColumns = 'Vorhandene Spalten ersetzen ?';

// ---------------------- dcpascal.pas ---------------

SErrExpectedButFound = '%s erwartet, aber %s gefunden';
SErrOrExpected = '%s oder  %s erwartet';
SErrFunDefined = 'Funktion %s ist schon definiert';
SErrunkn_id = 'Unbekanntes Identifiezierungszeichen: %s';
SErrunexp_writer = 'Unbekannter Variablentyp beim Schreiben des Programms';
SErrunit_declared = 'Unit %s ist schon definiert';
SErrbad_unit = 'Unit Deklarationsfehler';
SErrfun_notfound = 'Funktion %s nicht gefunden';
SErrlinker_error = 'Falscher Verweis';
SErrlabel_already = 'Label <%s> ist schon definiert';
SErrdeclpart = 'Fehler im Deklarationsblock';
SErrlab_notdef = 'Label <%s> ist nicht definiert';
SErrvar_already = 'Variable <%s> ist schon definiert';
SErrbad_varblock = 'Fehler im Variablen-Deklarationsblock';
SErrvar_NotDef = 'Variable <%s> ist nicht definiert';
SErrmeth_decerr = 'Methodendeklarations-Fehler';
SErrbad_methparam = 'Methodenparameters Deklarations-Fehler';
SErrno_props = 'Eigenschaften sind nicht erfüllt'; //implemented??
SErronly_class = 'Nur Klassendeklarationen sind erlaubt';
SErr_decl = '%s Deklarationsfehler';
SErrsynt_err = 'Schreibfehler in Zeile: %d  Buchstabe: %d'#13#10'%s';
SErrbad_idName = 'Falscher Name für Erkennungszeichen <%s>';
SErrbad_id = 'Falsches Erkennungszeichen <%s>';
SErrin_funuse = 'Unzulässiger Gebrauch der Funktion';
SErrin_procuse = 'Unzulässiger Gebrauch der Prozedur';
SErrbad_hex = 'Hex Konstantendeklarationsfehler';
SErrcompile_before = 'Vor dem Ausführen muß kompiliert werden';
SErrbad_realconst = 'Real Konstantendeklarationsfehler'; //real constant??
SErrbad_charconst = 'String Konstantendeklarationsfehler'; //String constant??
SErrunsup_partype = 'Nicht unterstützter Parameter Typ';
SErrno_resvar = 'Variablenergebniss für %s nicht gefunden';
SErrproc_notfound = 'Prozedur %s nicht gefunden';
SErrpar_notfound = 'Parameter %S nicht gefunden';
SErrUnknReaderType = 'Unbekannter Reader-Typ'; //reader
SErrInvalidParams = ' Falsche Parameterzahl';
SErrInvalidType = 'Einer der Parameter ist kein gültiger Varianttyp';
SErrInvalidProperty = 'Eigenschaft existiert nicht oder ist schreibgeschützt';
SErrInvalidCall = 'Benannte Argumente werden nicht unterstützt';
SErrParamNotFound = 'Parameter nicht gefunden';
SErrTypeMismatch = 'Parameter Typ stimmt nicht überein';
SErrInvalidInterface = 'Unbekannte Schnittstelle';
SErrParamOmitted = 'Ein erforderlicher Parameter fehlte';
SErrUnknown = 'Unbekanner Fehler';
SErrInvCode = 'unzulässiger Operationscode';

// ---------------------- csDelphi.pas ---------------
SClientDataFilter = 'Client DataSet (*.cds)|*.cds|Alle Dateien (*.*)|*.*';
SSaveToFile = 'Speichere als Date&i...';
SLoadFromFile = '&Lade aus Datei...';
SClientDSAssignData = 'weise Local &Data zu...';
// ---------------------- dcactnlst.pas ---------------

SDefaultCategory = 'Kein';

// ---------------------- AligUnit.pas ---------------

SAlignmentpalette = 'Ausrichtungspalette';
SAlignleft = 'Linke Kanten ausrichten';
SAlignhor = 'Horizontale Mitten ausrichten';
SCenterHor = 'Horizontal im Fenster zentrieren';
SSpaceeqHor = 'Abstand angleichen, Horizontal';
SAlignright = 'Rechte Kanten ausrichten';
SAligntops = 'Oberkanten ausrichten';
SAlignvert = 'Vertikale Mitten ausrichten';
SCentervert = 'Vertikal im Fenster zentrieren';
SSpaceeqVert = 'Abstand angleichen, vertikal';
SAlignbottom = 'Unterkanten ausrichten';
SVerbStayOnTop = '&an der Oberfläche bleiben';
SVerbHide = '&verstecken';

// ---------------------- DAlign.pas ---------------

SAlignment = 'Ausrichtung';
SHorizontal = ' Horizontal';
SVertical = ' Vertikal';
SHorizontalAlignment = 'Keine Änderung'#13#10'Linke Seiten'#13#10'Mitten'#13#10 +
'Rechte Seiten'#13#10'Abstand gleichmäßig'#13#10'Im Fenster zentrieren';
SVerticalAlignment = 'Keine Änderung'#13#10'Oberkanten'#13#10'Mitten'#13#10 +
'Unterkanten'#13#10'Abstand gleichmäßig'#13#10'Im Fenster zentrieren';

// ---------------------- DcImgEd.pas ---------------

SAskSeparateBitmaps = 'Bildgröße für %s ist größer als Bilderliste Größen. In %d separate Bilder aufteilen ?';
SVerbImageListEditor = 'Bil&derliste-Editor...';
SSelImage = 'Au&sgewähltes Bild';
STransColor = 'durchsich&tige Farbe';
SFillColor = '&Farbe ausfüllen';
SOptions = 'Optionen';
SCrop = 'Ab&schneiden'; //crop=abschneiden??
SStretch = 'De&hnen';
SCenter = 'Z&entrieren';
SApply = 'A&nwenden';
SAddImage = 'Hin&zufügen';
SDelete = '&Löschen';
SClear = '&Bereich löschen'; //clear??

// ---------------------- DcPalFrm.pas ---------------

SComPal = 'Komponentenpalette';

// ---------------------- dcstrled.pas ---------------

SOpen = 'Öffnen';
SCodeEdit = '&Code Bearbeiten...';

// ---------------------- dsize.pas ---------------

SSize = 'Größe';
SWidth = ' Breite';
SHeight = ' Höhe';
SHorizontalSize = 'Keine Änderung'#13#10'Zum kleinsten Schrumpfen'#13#10'Zum größten vergrößern'#13#10'Breite:';
SVerticalSize = 'Keine Änderung'#13#10'Zum kleinsten Schrumpfen'#13#10'Zum größten vergrößern'#13#10'Höhe:';

// ---------------------- glyphed.pas ---------------

SCopy = 'Kopieren';
SPaste = 'Einfügen';

// ---------------------- inspunit.pas ---------------

SInspectorTabs = 'Eigenschaften'#13#10'Ereignisse';
SVerbShowCategory = 'Zeige Kategorien';
SVerbDelphiStyle = 'Delphi Stil';
SVerbVBStyle = 'Visual Basic Stil';

// ----------------------MaskPr.pas ---------------

SInputMask = 'E&ingabemaske';
SCharBlank = 'Buchstabe für &Leerzeichen';
SSaveLiterChar = '&Literale speichern';
STestInput = '&Test Eingabe';
SMask = '&Masken...';

// ----------------------MskText.pas ---------------

SInputText = 'Text e&ingeben';
SEditMask = 'Maske Bearbeiten';

// ----------------------newfield.pas ---------------

SFieldName = '&Name';
SFieldType = '&Typ';

// ----------------------packcfg.pas ---------------

SAddPack = 'Paket hinzufügen/Register ActiveX';
SRemovePack = 'Paket entfernen';
SShowComp = 'Zeige Komponenten';

// ----------------------pstored.pas ---------------

SSelectAll = 'A&lles auswählen';
SUnselectAll = 'Rückgängig Alles a&uswählen';

// ----------------------replunit.pas ---------------

STextToFind = '&Suchen nach:';
SReplaceWith = '&Ersetzen durch:';
SCaseSensitive = 'Groß/&Kleinschreibung';
SWholeWord = '&Nur ganze Wörter';
SRegExpr = '&Reguläre Ausdrücke';
SPropmtRepl = '&Mit Bestätigung';
SDirection = 'Suchrichtung';
SForward = '&Vorwärts';
SBackward = 'Rück&wärts';

SScope = 'Bereich'; //scope=Umfang??
SGlobal = '&Gesamter Text';
SSelText = 'Mark&ierter Text';
SOrigin = 'Beginn';
SFromCursor = 'Ab &Cursor';
SEntireScope = '&Textanfang';
SReplAll = '&Alles ersetzen';

sReplace = 'Replace';
sClose = 'Close';

// ----------------------rerdlg.pas ---------------

SErrMess = '%s.  Fehler ignorieren und fortfahren? ACHTUNG: Den Fehler Ignorieren ' +
'kann dazu führen, daß Komponenten gelöscht werden oder Eigenschaftswerte' +
' verlorengehen';
SIgnoreAll = '&Alles ignorieren';

// ----------------------Searunit.pas ---------------

SFind = 'Suche';

// ----------------------TreeEd.pas ---------------

SRefresh = 'Aktualisieren';
SLevelUp = 'Eine Ebene nach oben';
SAddItem = 'Element hinzufügen';
SAddSubItem = 'Unterelement hinzufügen';
SDeleteItem = 'Lösche Element';
SLargeIcon = 'Großes &Symbol';
SSmalIcon = '&Kleines Symbol';
SListStyle = '&Liste';
SReportStyle = 'Be&richt';

// ----------------------MainUnit.pas -------------------------

SFileMenu = '&Datei';
SFileNewMenu = '&Neu...';
SFileNewAppMenu = 'Neue An&wendung';
SFileNewFormMenu = 'Neues F&ormular';
SFileNewDataModuleMenu = 'Neues Daten &Modul';
SFileOpenMenu = 'Ö&ffnen...';
SFileOpenWorkspaceMenu = 'Öffne &Workspace...';
SFileSaveWorkspaceMenu = 'Speichere Works&pace';
SFileSaveWorkSpaceAsMenu = 'Speichere WorkSpace als...';
SFileSaveAllMenu = 'Alles &Speichern';
SFileCloseAllMenu = 'Alles Sc&hließen';
SFileUseObjectMenu = '&Benutze Objekt...';
SFileAddtoprojectMenu = 'Zum &Projekt hinzufügen...';
SFileRecentFilesMenu = '&Zuletzt benutzte Dateien';
SFileRecentWorkSpacesMenu = 'R&ecent WorkSpaces';
SFilePrintMenu = 'D&rucken...';
SFileExitMenu = '&Ende';
SEditMenu = '&Bearbeiten';
SEditUndoMenu = '&Rückgängig';
SEditRedoMenu = '&Widerrufen';
SEditCutMenu = '&Ausschneiden';
SEditCopyMenu = '&Kopieren';
SEditPasteMenu = '&Einfügen';
SEditLockControlsMenu = 'Komponenten fi&xieren';
SSearchMenu = '&Suchen';
SSearchFindMenu = 'Suc&he...';
SFindinFilesMenu = 'Suche in &Dateien...';
SSearchReplaceMenu = 'Erset&zen...';
SSearchSearchAgainMenu = 'Suche &wiederholen';
SIncrementalSearchMenu = '&Inkrementelle Suche';
SSearchGotoLineMenu = 'Zeilen&nummer...';
SViewMenu = '&Ansicht';
SViewProjectManagerMenu = '&Projektverwaltung';
SViewAlignmentPaletteMenu = '&Ausrichtungspalette';
SViewToggleFormUnitMenu = '&Umschalten Formular/Unit';
SViewWindowListMenu = '&Fensterliste...';
SViewNewEditWindowMenu = 'Neues Editie&rfenster';
SViewClipboardHistoryMenu = 'Verlauf Zwis&chenablage';
SViewPackagesMenu = '&Pakete/ActiveX';
SRunMenu = 'Sta&rt';
SRunQuickRunMenu = '&External Run'; //?? -externes programm ausführen??
SRunParametersMenu = '&Parameter...';
SRunProgramResetMenu = 'Programm &zurücksetzen';
SEvaluateModifyMenu = 'Aus&werten/ändern';
SToolsMenuMenu = '&Tools';
SToolsOptionsItemMenu = '&Umgebungsoptionen...';
SIDEInspectorMenu = 'I&DE inspektor';
SHelpMenu = '&Hilfe';
SHelpContentsMenu = '&Inhalt...';
SHelpHomePageMenu = '&Home Page';
SHelpWritetousMenu = '&Schreiben Sie uns';
SHelpOnlineregMenu = '&Online Registrierung';
SHelpAboutMenu = 'Inf&o...';
SPopupComponentsMenu = 'K&omponenten...';

// ----------------------OptUnit.pas -------------------------

SPreferences = 'Voreinstellungen';
SVbStyle = 'VB Stil';
SDelphiStyle = 'Delphi Stil';
SShowCategory = 'Zeige Kategorien';
SOInspector = 'Objektinspektor';
SSmartPopup = 'Smart popup';
SShowHints = 'Zeige &Hinweise';
SEditAliases = 'Aliasse editieren';
SFormDesigner = 'Formular-Designer:';
SGridStepX = 'Rastergröße &X';
SGridStepY = 'Rastergröße &Y';
SDisplayGrid = '&Raster anzeigen';
SSnapToGrid = 'Am Gitter aus&richten';
SShowCaptions = 'Komponenten-&Titel zeigen';
SDsgnHints = 'Designer &Hinweise';
SEditor = 'Editor';
STabStops = '&Tabstops:';
SBlockIndent = 'Block ein&rückung:';
SKeyMappings = 'Ta&staturbelegung:';
SEditorOptions = 'Editoroptionen:';
SAutoIndentMode = '&Automatischer Zeileneinzug';
SSmartTab = 'A&utomatische Tabs';
SBackUnindents = 'Rücktaste &löscht Einzug'; //??
SShowLineNumbers = 'Zeige Zeilen&nummern';
SShowLineNumbersOnGutter = 'Zeige Zeilennummern au&f Leiste';
SGroupUndo = '&Gruppe rückgängig';
SCursorBeyondEof = 'Cursor hinter &EOF';
SKeepTrailingBlanks = 'Leerze&ichen am Zeilenende erhalten';
SPersistentBlocks = '&Persistente Blöcke'; //persistent =hartnäckig??
SOverwriteBlocks = 'Blöcke ü&berschreiben?';
SDblClickLine = 'Doppel&klick markiert Zeile';
SFindTextAtCursor = 'Te&xt am Cursor suchen';
SCutCopyEnabled = 'Ausschn./Kopieren immer akti&v';
SSyntaxHighlighting = 'S&yntaxhervorhebung benutzen';

SCursorByondEol = '&Cursor hinter Zeilenende';
SSelectionByondEol = 'Aus&wahl hinter Zeilenende';
sDisplaySpecialChars = 'Display Special Chars';
SOverCaretBlock = 'Übersc&hreibe-Cursor als Block';
SDisableDrag = '&Dragging ausschalten';

SDisplay = 'Anzeige';
SEditFont = '&Editorschrift:';
SUseMonoFont ='N&ur Nichtproportionale Schriften benutzen';
SOptionSize = '&Größe:';
SEditMargin = 'Rechter &Rand:';
SColor = '&Farbe:';
SStyle = 'S&til:';
SOptionWidth = '&Breite:';
SPosition = '&Position:';
SVisible = '&sichtbar';
SEditGutter = 'Editorleiste links:';
SColors = 'Farben';
SElements = '&Element:';
SColorSpeedSetting = 'Farbs&chema:';
STextAttrs = ' Textattribute: ';
SBackColor = '&Hintergrundfarbe:';
SForeColor = '&Vordergrundfarbe:';

SBoldFont = 'Fet&t';
SItalicFont = '&Kursiv';
SUnderLineFont = '&Unterstrichen';

//----------------diffmake.pas------------------------

SErrCRC = 'CRC Fehler';
SErrSmallBuffer = 'Puffergröße sollte mindestens 4 Bytes betragen';

//------------formfill.pas---------------------------

SErrFillTypeStarted = 'Fülltyp wurde bereits gestartet';

//---------editunit.pas--------------------------------------

SOpenFileatCursor = 'Ö&ffne Datei am Cursor';
SBrowseSymbolatCursor = '&Durchsuche Symbol am Cursor';
STopicSearch = 'Themen&suche';
SToggleBreakpoint = 'Haltepunkte umschalten';
SRuntoCursor = 'RStart bis zum C&ursor';
SAddWatchatCursor = 'Füge Über&wachung am Cursor hinzu...';
SViewasForm = '&Ansicht als Formular';
SReadOnly = 'Schrei&bgeschützt';
SClosePage = 'Seite s&chließen';
SMessageView = '&Meldungsfenster';

//new
//---------dcmenu.pas--------------------------------------

sErrNotAForm = 'DCMenu kann nur in einem Formular plaziert werden';

//---------dcpascal.pas--------------------------------------

SErrMisplacedBreak = 'Unterbrechung außerhalb der Schleife';
SErrMisplacedContinue = 'Fortsetzung außerhalb der Schleife';

//---------dcstdctl.pas--------------------------------------

SErrCircularReference = 'Zirkuläre Referenz';

//---------dtreeed.pas--------------------------------------

SNewNode = 'Neuer Knoten';

//--------------------------------------------------------

//Memo print messages
SFileNameUnknown = '<Unbekannt>';
SFileSelectedBlock = '<Markierter Block>';
SPrintingPage = 'Drucke Seite %d von %s';
SPageCaption = 'Seite %d/%d';
SMultiDot = ' ... ';
SPrintingOnPrinter = 'Drucke auf Drucker %s';

//Print progress messages
SPrintStatus = 'Druckerstatus';
SSearchPrinters = 'Suche Drucker ...';
SPrintProgress = 'Drucke Seiten :      Berechnung ...';

//Print Dialog messages
SPrintFormCaption = 'Druckoptionen';
SPrintFormCaptionSelection = 'Druckerwahl';
SPrintDestCaption = 'Zu druckende Datei:';
SPrintSelectedBlock = '&Markierten Block drucken';
SOptionsCaption = 'Optionen:';
SSetupButton = '&Einstellungen...';
SHeaderPage = 'Überschrift/Seiten&nummer';
SFooterPage = '&Fußzeile';
SLineNumber = '&Zeilennummern';
SSyntaxPrint = '&Syntaxhervorhebung';
SUseColor = 'Farben &verwenden';
SShowPrintProgress = 'Druckf&ortschritt &anzeigen';
SWrapLines = 'Zeilen &umbrechen';
SLeftMargin = 'Linker &Rand:';

//------------- Info Tree constants -------------------------

SErrReferencedObject = 'Objekt hat Referenzen von einem anderen Objekt';

SErrEmptyLink = '%s: Link ist nicht angegeben';
SIUnknownNotSupported = 'IUnknown wird nicht unterstützt';
SIDCRowSetNotSupported = 'IDCRowSet wird nicht unterstützt';
SErrActiveObject = 'Objekt ist aktiv. bitte schliessen Sie es';
SErrNonActiveInfoSet = 'InfoSet ist nicht aktiv. Bitte öffnen Sie es';
SErrUnsupportedDataType = 'Der Datentyp von Feld "%s" wird nicht unterstützt';
SErrSetInfoSet = 'Bitte setzen Sie die InfoSet-Eigenschaft';
SErrFieldReadOnly = 'Feld "%s" ist schreibgeschützt';
SErrFieldDestroyed = 'Feld "%s" ist zerstört';
SErrHandlerAlreadyExists = 'Handler existiert bereits';
SErrHandlerNotExists = 'Handler existiert nicht';
SErrObjectIsNull = 'Objekt ist NULL';
SIDCMasterInfoSetNotSupported = 'IDCMasterInfoSet  wird nicht unterstützt';
SErrInsert = 'Kann Knoten nicht hinzufügen';
SErrChangesNotSupported = 'Infoset unterstützt keine Änderungen';

//ReliInfoSet messages
SErrFieldNotFound = 'Felder "%s" wurden nicht gefunden.';

SErrSetReliItem = 'Bitte setzen Sie die %s-Eigenschaft';
SErrCMastAndDetDifferent = 'Detail und Masterfeldnummern passen nicht zusammen';
SErrRelFieldNotFound = 'Felder "%s" wurden nicht gefunden.';
SErrEmptyDisplayField = 'leerer Anzeigename';
SErrIncompatibleDataType = 'Die Typen des Masters "%s" und des Details "%s" sind inkompatibel';

SErrSetReliItemIndex = 'Bitte setzen Sie die %s-Eigenschaft. Fehler im %d. Element';
SErrCMastAndDetDifferentIndex = 'Detail- und Masterfeldnummern passen nicht zusammen. Fehler im %d. Element';
SErrRelFieldNotFoundIndex = 'Felder "%s" wurden nicht gefunden.  Fehler im %d. Element';
SErrEmptyDisplayFieldIndex = 'Leerer AnzeigeName. Fehler im %d. Element';
SErrIncompatibleDataTypeIndex = 'Die Typen des Masters "%s" und des Details "%s" sind inkompatibel. Fehler im %d. Element';

SErrInvalidFilter = 'Ungültig geformter Filterausdruck';
SErrInvalidFieldType = 'Ungültiger Feldtyp';
SErrSetDataSet = '%s: Bitte setzen Sie die DataSet-Eigenschaft';
SErrSetRootDataSet = '%s: Bitte setzen Sie die RootDataSet-Eigenschaft';
SErrNotInfoSetDataSet = 'Wert muß vom Typ TDataSet oder InfoSet sein';

//InfoDB constants
SErrUniqueFieldAlreadyRegistered = 'Es ist bereits ein Unique Feld registriert';
SErrUniqueFieldIsNotRegistered = 'Für dieses DataSet ist kein unique Feld registriert';
SErrInvalidBookmark = 'Ungültiges Lesezeichen';

SErrScriptLanguageNotSpecified = 'Scripting Sprache ist nicht angegeben';

//TSyntaxScheme
SCantReadSSchemeFrom = 'Kann Syntaxschema nicht einlesen aus Datei ';
SFromFile = 'Datei';
SFromStream = 'Stream';
SSchemeEditor = 'Scheme Editor...'; //!
SFirstCharAccent = ''; //in most cases this const should be empty
SOtherCharAccent = ''; //in most cases this const should be empty

//TSyntaxScheme Editor section
SSSETitle = 'TSyntaxSchema Editor';
SSchemeName = 'Schema &Name:';
SBlocks = '&Blöcke';
SExtensions = '&Erweiterungen';
SLoad = 'Laden';
SSave = 'Speichern';
SLoad1 = '&Öffnen';
SSave1 = '&Speichern';
SSaveAs = 'Speichern als';
SClear0 = 'Löschen';
SApply0 = 'Anwenden';
SBlkDelimiters = 'Block&begrenzer:';
SBlkOptions = 'Blockoptionen:';
SCaseSens = '&Groß-/Kleinschreibung';
SUseMeta = 'Benutze &MetaSymbol';
SMetaEscape = 'für &Escapes';
SMetaWrapLines = 'für &Zeilenumbruch';
SStyleText = 'Einfacher &Text:';
SUseSymbols = 'S&ymbole hervorheben';
SPageCommon = 'Common';
SPageComments = 'Kommentare';
SPageFullLine = 'FullLine';
SPageStrings = 'Strings';
SPageNumbers = 'Zahlen';
SPageIdents = 'Identifiers';
SPageKeywords = 'Schlüßelworte';
SPagePopups = 'Popups';
SAdd = 'Hinzufügen';
SRemove = 'Entfernen';
SEdit = 'Bearbeiten';
SAdd1 = '&Hinzufügen';
SRemove1 = '&Entfernen';
SEdit1 = '&Bearbeiten';
SAdd2 = 'H&inzufügen';
SRemove2 = 'E&ntfernen';
SEdit2 = 'Bearbei&ten';
SStyleButton = 'Stil...';
SUseComments = '&Kommentare hervorheben';
SUseCommentsSL = 'E&inzeilige Kommentare';
SUseCommentsML = '&Mehrzeilige Kommentare';
SUseCommentsFL = 'Kommentare über &ganze Zeile';
SUseDirectives = '&Direktiven hervorheben';
SUseStrings = 'Strin&gs hervorheben';
SUseStringsSL = 'E&inzeilige Strings';
SUseStringsML = '&Mehrzeilige Strings';
SUseNumbers = 'N&ummern hervorheben';
SIntNum = 'Inte&ger:';
SFloatNum = '&Fliesskomma:';
SHexNum = '&Hexadezimal:';
SPSNumbers = ' Spezial: ';
SWithPrefix = 'mit &Prefix';
SWithSuffix = 'mit Su&ffix';
SWithPS = 'm&it Prefix && Suffix';
SWithPrefixes = 'Mit Prefi&xen';
SWithSuffixes = 'Mit Suffi&xen';
SWithPSs = 'Mit Prefi&xen und Suffixen';
SMultiSuffixes = 'mehrfache Suffixe erlau&bt';
SPSComposition = '&Komposition von P && S';
SUseIdentifiers = 'I&dentifier hervorheben';
SCaptionFirstChar = 'First Symbol CharSet:'; //!
SCaptionOtherChar = 'Other Symbols CharSet:'; //!
SCaptionCharSet = '&CharSet:';
SUseKeywords = '&Schlüsselworte hervorheben:';
SKWSets = ' Mengen: ';
SCurKWSets = ' Derzeitige Schlüsselwortmenge: ';
SFontName = 'Schrift&name:';
SFontSize = 'Schriftgrö&sse:';
SFontColor = 'Schrift&farbe:';
SFontStyles = 'Schriftstil:';
SBackColor1 = '&Hintergrundfarbe:';
SBold = 'Fe&tt';
SItalic = '&Kursiv';
SUnderline = '&Unterstrichen';
SStrikeout = '&Durchgestrichen';
STextStyle = 'Te&xt Style:'; //!
SUseDefFont = 'Standardschrift benutzen';
SUseDefBack = 'Standardhintergrundfarbe benutzen';
SArePartOfBlock = 'Sind &Teil des Blocks';
SSelectBlock = 'Blockaus&wahl:';
SFilterScheme = 'Syntax Schema Dateien (*.sch)|*.sch|Alle Dateien (*.*)|*.*';
SFilterKeywords = 'Textdateien (*.txt)|*.txt|Alle Dateien (*.*)|*.*';
SCaptionSet = 'Menge:';
SCaptionKeyword = '&Schlüsselwort:';
SCaptionDelimiter = '&Begrenzer:';
SCaptionLeftDlmtr = '&Linker Begrenzer:';
SCaptionRightDlmtr = '&Rechter Begrenzer:';
SCaptionPrefix = 'Prefix:';
SCaptionSuffix = 'Suffix:';
SCaptionBlock = '&Block:';
SCaptionParent = '&Parent:';
SCaptionExt = 'Er&weiterung:';
SQueryRemoveBlock = 'Wollen Sie den Syntaxblock wirklich löschen?';
SQueryRemoveKWSet = 'Wollen Sie die Schlüsselwortmenge wirklich löschen?';
SAnd = ' und ';

//DC Menu Designer
sDCMenuDesigner = 'Menu Designer...';
sDCMenuValue = '(Menu)';
sDCInsertMenuItemCaption = '&Hinzufügen';
sDCDeleteMenuItemCaption = '&Löschen';
sDCCreateSubMenuMenuItemCaption = 'Erzeuge &Untermenu';
sDCSelectMenuItemCaption = 'Menu aus&wählen...';
sDCSelectMenuFormCaption = 'Menuauswahl';

//=================== UNTRANSLATED SECTION ===================
{------------ This section will be translated ---------------}

//InspUnit OI Descriptions
SDescrName = 'Name=Returns/sets the name used in code to identify an object.';
SDescrCaption = 'Caption=Returns/sets the text displayed in an objects''s title bar or below an object''s icon.';
SDescrBorderStyle = 'BorderStyle=Returns/sets the border style for an object.';
SDescrCtl3d = 'Ctl3d=Returns/sets whether or not an object is painted at run time with 3-D effects.';
SDescrKeyPreview = 'KeyPreview=Returns/sets whether keyboard events for an object are invoked before keyboard events for controls on that object.';
SDescrHeight = 'Height=Returns/sets the height of an object.';
SDescrLeft = 'Left=Returns/sets the distance between the internal left edge of an object and the left edge of its container.';
SDescrTop = 'Top=Returns/sets the distance between the internal top edge of an object and the top edge of its container.';
SDescrWidth = 'Width=Returns/sets the width of an object.';
SDescrWindowState = 'WindowState=Returns/sets the visual state of a form window at run time.';
SDescrVisible = 'Visible=Returns/sets a value that determines whether an object is visible or hidden.';
SDescrPosition = 'Position=Returns or sets a value specifying the position of a Form when it first appears.';
SDescrCursor = 'Cursor=Returns/sets the type of mouse pointer displayed when over part of an object.';
SDescrIcon = 'Icon=Returns the icon displayed when a form is minimized at run time.';
SDescrHelpContext = 'HelpContext=Specifies the default Help file context ID for an object.';
SDescrEnabled = 'Enabled=Returns/sets a value that determines whether an object can respond to user-generated events.';
SDescrDragMode = 'DragMode=Returns/sets a value that determines whether manual or automatic drag mode is used.';
SDescrPasswordChar = 'PasswordChar=Returns/sets a value that determines whether characters typed by a user or placeholder characters are displayed in a control.';
SDescrScrollBars = 'ScrollBars=Returns/sets a value indicating whether an object has vertical or horizontal scroll bars.';
SDescrHint = 'Hint=Returns/sets the text displayed when the mouse is paused over the control.';
SDescrDataField = 'DataField=Returns/sets a value that binds a control to a field in the current record.';
SDescrDataSource = 'DataSource=Sets a value that specifies the Data control through which the current control is bound to a database.';
SDescrAutoSize = 'AutoSize=Determines whether a control is automatically resized to display its entire contents.';
SDescrInterval = 'Interval=Returns/sets the number of milliseconds between calls to a Timer control''s OnTimer event.';
SDescrTag = 'Tag=Stores any extra data needed for your program.';
SDescrTabStop = 'TabStop=Returns/sets a value indicating whether a user can use the TAB key to give the focus to an object.';
SDescrTabIndex = 'TabIndex=Returns/sets the tab order of an object within its parent control.';
SDescrShape = 'Shape=Returns/sets a value indicating the appearance of a control.';
SDescrCancel = 'Cancel=Indicates whether a command button is the Cancel button on a form.';
SDescrDefault = 'Default=Determines which button control is the default command button on a form.';
SDescrColor = 'Color=Returns/sets the background color of the component.';
SDescrFont = 'Font=Returns/sets the font characteristics of the component, including typeface, size, attributes and color.';
SDescrParentFont = 'ParentFont=Determines where a control looks for its font information.';
SDescrShowHint = 'ShowHint=Determines if the control should display a hint when the mouse pointer rests momentarily on it.';
SDescrPopupMenu = 'PopupMenu=Identifies the pop-up menu associated with the control.';
SDescrActiveControl = 'ActiveControl=ActiveControl is the control that has focus on the form.';
SDescrScaled = 'Scaled=Specifies whether the form is sized according to the value of the PixelsPerInch property or not.';
SDescrPrintScale = 'PrintScale=Value that represents the proportions of a printed form.';
SDescrAutoScroll = 'AutoScroll=Specifies whether scroll bars appear automatically on the scrolling windowed control or not.';
SDescrBorderIcons = 'BorderIcons=Set of values that specify which icons appear on the title bar of the form.';
SDescrClientHeight = 'ClientHeight=Height of the control''s client area in pixels.';
SDescrClientWidth = 'ClientWidth=Width of the control''s client area in pixels.';
SDescrWindowMenu = 'WindowMenu=Window menu for an MDI parent form.';
SDescrFormStyle = 'FormStyle=Set of values that represent the form''s style.';
SDescrHelpFile = 'HelpFile=Specifies the name of the file the application uses to display Help.';
SDescrMenu = 'Menu=Form''s main menu.';
SDescrObjectMenuItem = 'ObjectMenuItem=OLE object menu item that reacts to selections of OLE objects.';
SDescrPixelsPerInch = 'PixelsPerInch=Value that represents the proportion of the font on the system on which the form was designed.';
SDescrHorzScrollBar = 'HorzScrollBar=An object that encapsulates the horizontal scroll bar for the scrolling windowed control.';
SDescrVertScrollBar = 'VertScrollBar=An object that encapsulates the vertical scroll bar for the scrolling windowed control.';
SDescrFontCharSet = 'Font.CharSet=Specifies the character set of the font.';
SDescrFontColor = 'Font.Color=Specifies the color of the text.';
SDescrFontHeight = 'Font.Height=Specifies the height of the font.';
SDescrFontName = 'Font.Name=Identifies the typeface of the font.';
SDescrFontPitch = 'Font.Pitch=Specifies whether the characters in the font all have the same width.';
SDescrFontSize = 'Font.Size=Size is the height of the font in points.';
SDescrFontStyle = 'Font.Style=Determines whether the font is normal, italic, underlined, bold, and so on.';
SDescrOnActivate = 'OnActivate=Occurs when the object becomes active.';
SDescrOnClick = 'OnClick=Occurs when the user clicks the control.';
SDescrOnClose = 'OnClose=Occurs when the form closes.';
SDescrOnCloseQuery = 'OnCloseQuery=Occurs when the Close method is called or when the user closes from using system menu.';
SDescrOnCreate = 'OnCreate=Occurs when the form is created.';
SDescrOnDblClick = 'OnDblClick=Occurs when the user double-clicks mouse button when the mouse is over the control.';
SDescrOnDestroy = 'OnDestroy=Occurs when the form is destroyed.';
SDescrOnDeactivate = 'OnDeactivate=Occurs when the form loses focus.';
SDescrOnDragDrop = 'OnDragDrop=Occurs when the user drops an object being dragged.';
SDescrOnDragOver = 'OnDragOver=Occurs when the user drags an object over a control.';
SDescrOnHide = 'OnHide=Occurs when the form is going to be hidden.';
SDescrOnHelp = 'OnHelp=Occurs when the form receives a request for help.';
SDescrOnKeyDown = 'OnKeyDown=Occurs when a user presses any key while the control has focus.';
SDescrOnKeyPress = 'OnKeyPress=Occurs when a user presses a single character key.';
SDescrOnKeyUp = 'OnKeyUp=Occurs when the user releases a key that has been pressed.';
SDescrOnMouseDown = 'OnMouseDown=Occurs when the user presses a mouse button with the mouse pointer over a control.';
SDescrOnMouseMove = 'OnMouseMove=Occurs when the user moves the mouse pointer while the mouse pointer is over a control.';
SDescrOnMouseUp = 'OnMouseUp=Occurs when the user releases a mouse button that was pressed with the mouse pointer over a component.';
SDescrOnPaint = 'OnPaint=Occurs when the object is redrawn.';
SDescrOnResize = 'OnResize=Occurs when the object is resized.';
SDescrOnShow = 'OnShow=Occurs when the object is shown.';

sDCErrorPrefix = '[Error]';

sDCNewMenuCaption    = '&New';
sDCOpenMenuCaption   = '&Open';
sDCSaveMenuCaption   = '&Save';
sDCSaveAsMenuCaption = 'Save &As...';
sDCExitMenuCaption   = '&Exit';

sDCNewActionHint    = 'New';
sDCOpenActionHint   = 'Open';
sDCSaveActionHint   = 'Save';
sDCSaveAsActionHint = 'Save as...';
sDCExitActionHint   = 'Exit';

sDCProcessStatusLabelCaption = 'Process status:';

//================= END UNTRANSLATED SECTION =================

// Component Palette
sDCCannotSaveToRegistry = 'Beim Versuch, die Paletteneinstellungen in der Registry zu speichern ist ein Fehler aufgetreten';
sDCIndexOutOfBound      = 'Index ausserhalb der zulässigen Grenzen';

sLessButton = '&Less';
sMoreButton = '&More';
sReplacements = '%d replacements have been made';
sFindAndRepl = 'Find and Replace';
sGoTo = 'Go To';
sLine = 'Line';
sBookMark = 'BookMark';
sErrBookmarNotFound = 'Bookmark %d not found';

const
sWithClause = 'mit';
sWithOutClause = 'ohne';


//Object Inspector Aliases
const
  DefaultInspectorAliases = (
    '[Appearance]'#13#10+
    'Color'#13#10+
    'Caption'#13#10+
    'Cursor'#13#10+
    'Alignment'#13#10+
    'ParentColor'#13#10+
    'Transparent'#13#10+
    'WordWrap'#13#10+
    'Flat'#13#10+
    'Glyph'#13#10+
    'Ctl3d'#13#10+
    ''#13#10+
    '[Behavior]'#13#10+
    'OnEditButtonClick'#13#10+
    'OnEnter'#13#10+
    'OnExit'#13#10+
    'TabOrder'#13#10+
    'TabStop'#13#10+
    'DragCursor'#13#10+
    'DragMode'#13#10+
    'Cancel'#13#10+
    'Default'#13#10+
    'Enabled'#13#10+
    'Visible'#13#10+
    'GroupIndex'#13#10+
    'ImeMode'#13#10+
    'ImeName'#13#10+
    ''#13#10+
    '[List]'#13#10+
    'IntegralHeight'#13#10+
    'ItemHeight'#13#10+
    'Items'#13#10+
    'MultiSelect'#13#10+
    ''#13#10+
    '[Font]'#13#10+
    'Font'#13#10+
    'ParentFont'#13#10+
    ''#13#10+
    '[Misc]'#13#10+
    'Name'#13#10+
    'PopupMenu'#13#10+
    'HelpContext'#13#10+
    'Tag'#13#10+
    'FocusControl'#13#10+
    ''#13#10+
    '[Hint]'#13#10+
    'ParentShowHint'#13#10+
    'ShowHint'#13#10+
    'Hint'#13#10+
    ''#13#10+
    '[Position]'#13#10+
    'Height'#13#10+
    'Top'#13#10+
    'Left'#13#10+
    'Width'#13#10+
    'Autosize'#13#10+
    'Align'#13#10+
    ''#13#10+
    '[Data]'#13#10+
    'DataSource'#13#10+
    'DataSet'#13#10+
    'DataField'#13#10+
    ''#13#10+
    '[Keyboard]'#13#10+
    'OnKeyDown'#13#10+
    'OnKeyPress'#13#10+
    'OnKeyUp'#13#10+
    ''#13#10+
    '[Mouse]'#13#10+
    'OnClick'#13#10+
    'OnDblClick'#13#10+
    'OnMouseDown'#13#10+
    'OnMouseMove'#13#10+
    'OnMouseUp'#13#10+
    ''#13#10+
    '[DragDrop]'#13#10+
    'OnDragDrop'#13#10+
    'OnDragOver'#13#10+
    'OnEndDrag'#13#10+
    'OnStartDrag'
    );

sDCComponentsListFormCaption = 'Komponenten';
sDCComponentsListPanelCaption = '&Installierte Komponenten';

//=================== UNTRANSLATED SECTION ===================
sDCProcedures = 'Procedures';
sDCClasses    = 'Classes';
sDCTypes      = 'Types';
sDCVariales   = 'Variables';
sDCConstants  = 'Constants';
sDCProperties = 'Properties';
sDCMethods    = 'Methods';

sDCNoFieldsAreAvailable = 'No fields are available.';

sDCSourceLabel      = 'Available fields:';
sDCDestinationLabel = 'Participating fields:';

sDCActiveXEditorCaption = 'ActiveXs';

sUseTabChar = '&Use tab character';

//================= END UNTRANSLATED SECTION =================

sDCActiveXPanelCaption = 'Design &ActiveXs';
sDCComponentsBtnCaption = '&Komponenten';

sDCPackagesEditorCaption = 'Packages';
sDCPackagesPanelCaption = 'Design &packages';
sDCRemoveBtnCaption = '&Entfernen';
sDCEditBtnCaption = 'Ä&ndern';

//TreeNodesEditor
STrEdCaption = '.Items Editor';
SNodeTypeNone = 'None';
SNodeTypeCheckBox = 'CheckBox';
SNodeTypeRadioButton = 'RadioButton';
SStateUnchecked = 'Unchecked';
SStateChecked = 'Checked';
SStateGrayed = 'Grayed';
STrEdNewItem = 'New Ite&m';
STrEdNewSubItem = 'New Su&bItem';
STrEdClear = 'Clea&r';
STrEdMoveUp = 'Move &Up';
STrEdMoveDown = 'Move Do&wn';
STrEdDragNDropAsChild = 'Drag''n''Drop as child';
STrEdItemProperties = 'Item Properties';
STrEdText = 'Te&xt:';
STrEdIndexes = 'Indexes:';
STrEdImage = '&Image:';
STrEdSelected = 'S&elected:';
STrEdStateIndex = 'S&tate:';
STrEdOverlay = 'O&verlay:';
STrEdParentFont = '&Parent Font';
STrEdFont = '&Font:';
STrEdParentColor = 'Parent C&olor';
STrEdColor = '&Color:';
STrEdType = 'T&ype:';
STrEdAllowGrayed = 'Allow &Grayed';
STrEdState = 'St&ate:';
STrEdReadOnly = 'Read-O&nly';


SCannotCreateName = 'Cannot create a method for an unnamed component';
