{
  Translated to Spanish by Luis Alfonso Moreno
  Jos‚ Luis Santiago
}

SKBDClassic = 'Clasico';
SKBDBrief = 'Brief';
SKBDEpsilon = 'Epsilon';
SKBDVisualStudio = 'Visual Studio';

STSDefaults = 'Defaults';
STSClassic = 'Classic';
STSOcean = 'Ocean';
STSTwilight = 'Twilight';

SVerbActionListEditor = 'ActionList Editor...';
SVerbStandardAction = 'New Standard Action...';

// ------------------- New Object captions -----------------

SErrAlreadyInNewDialog = '%s ya esta registrado para el Nuevo Dialogo';

SDelphiApp = 'Aplicación Delphi';
SVBScriptApp = 'Aplicación VBScript';
SJScriptApp = 'Aplicación JScript';
SPerlApp = 'Aplicación Perl';
SPythonApp = 'Aplicación Python';

SDelphiForm = 'Formulario Delphi';
SVBScriptForm = 'Formulario VBScript';
SJScriptForm = 'Formulario JScript';
SPerlForm = 'Formulario Perl';
SPythonForm = 'Formulario Python';

SDelphiDataModule = 'Módulo de Datos Delphi';
SVBScriptDataModule = 'Módulo de Datos VBScript';
SJScriptDataModule = 'Módulo de Datos JScript';
SPerlDataModule = 'Módulo de Datos Perl';
SPythonDataModule = 'Módulo de Datos Python';

STextFile = 'Archivo de Texto';
SHTMLtext = 'Archivo HTML';
SSqltext = 'Archivo SQL';

SDelphiUnit = 'Unidad de Delphi';
SJScriptUnit = 'Unidad de JScript';
SVBScriptUnit = 'Unidad de VBScript';
SPerlUnit = 'Unidad de Perl';
SPythonUnit = 'Unidad de Python';

SDelphiReport = 'Informe de Delphi';
SPerlReport = 'Informe de Perl';
SVBScriptReport = 'Informe de VBScript';
SJScriptReport = 'Informe de JScript';
SPythonReport = 'Informe de Python';
SSimpleReport = 'Informe Sencillo';

SSimpleForm = 'Formulario Simple';
SSimpleDataModule = 'Módulo de Datos Simple';

SProjectFile = 'Archivo de Proyecto';
SWorkSpaceFile = 'Archivo de Espacio-de-Trabajo';

//--------------------- File Types captions --------------

SAllFiles = 'Todos los archivos';
SUnitFiles = 'Archivos de Unidades';
//=================== UNTRANSLATED SECTION ===================
{------------ This section will be translated ---------------}
sDelphiFiles = 'Delphi units';
sInterfaceFiles = 'Interface files';
sTextFiles = 'Text files';
//================= END UNTRANSLATED SECTION =================
SProjectWorkSpace = 'Proyecto/Espacio-de-Trabajo';
SFormFile = 'Archivo de Formulario';

//--------------------- Verb captions --------------

SVerbMenuItems = 'Editar &Elementos...';
SVerbSave = '&Guardar';
SVerbSaveAs = 'Guardar c&omo...';
SVerbClose = 'C&errar';
SVerbActivateProject = 'Activar Proyecto';
SVerbAdd = 'A&gregar...';
SVerbSQLEditor = 'Editor de SQL...';
SVerbResourceMaster = 'Experto en Recursos';
SVerbIdeInspector = 'Inspector del IDE';
SVerbMultiSourceEditor = 'Editar Fuentes...';

SRegPackages = 'Paquetes';

//--------------------- Parser Errors ----------------------------

SErrCharPos = ' en la Linea:%d, Carac:%d. ';
SErrMaxIfDefReached = 'Solo se permiten %d niveles de anidación en las directivas del compilador';
SErrCompilerDirective = 'Directiva del compilador invalida: "%s"';
STokenListEmpty = 'La lista de simbolos esta vacía';
SErrFutureState = 'Estado futuro';
SErrTokenExpected = 'Simbolo %d esperado';

// -------------------- Other Errors -------------------------

SErrFormNameEmpty = 'El nombre del formulario no puede estar vacío';
SErrMethodReferenced = 'El método referenciado %s no existe. ¿Eliminar la referencia?';
SErrControlsInData = 'No se pueden añadir controles a un Módulo de Datos';
SErrInvalidModuleClass = 'Clase de Módulo Invalido - %s';
SErrCreatingForm = 'Error al crear el formulario';
SErrUpdateRes = 'Error al actualizar el recurso';
SErrOnlyForms = 'Esta version del Experto en Recursos solo puede editar formularios';
SErrAlreadyInProject = 'El Objeto con el nombre "%s" ya se encuentra en el proyecto';
SErrOnlyWin32FileSystem = 'Esta operación solo puede ser efectuada en un sistema con Win32';
SErrObjectNotInProject = 'El objeto %S no se encuentra en el proyecto activo';
SErrNotInstantReport = 'Solo puede ser insertado en TInstantReport';
SErrAlreadyUseAll = 'El objeto %S ya usa todos los objetos disponibles';
SErrBadPropStream = 'Error en el stream de propiedades';
SErrNoComp = 'El Componente %s no existe';
SErrAlreadyHaveOwner = 'Este Espacio-de-Trabajo ya tiene propietario';
SErrNonMonoSpacedFont = 'Solo fuentes monoespaciadas pueden ser utilizadas';
SerrInvalidMoving = 'No lo puedo mover aquí';
sErrCantOpen = 'No puedo abrir el módulo %s'#13#10'Codigo de Error : %d';
SErrNoNewExtensions = 'Nuevas extensiones no instaladas';
SErrOpenFile = 'Error al abrir %s';
SErrorCreateMap = 'Error al crear archivo de mapeo';
SErrorMap = 'No puedo mapear %s en la memoria';
SErrReadOnlyFile = '''%s'' es un archivo de solo-lectura';

//------------------Scripter constants ----------------------------------

//  SErrScriptEngineRun = 'No puedo iniciar el motor del interprete';
SErrScriptEngineRun = 'No se puede iniciar el motor de Scripting';
SErrAlreadyLaunched = 'El programa ya ha sido iniciado';
SErrNoCodeDesigner = 'No hay diseñador de código registrado para este tipo de archivo %s';
SErrNoScriptRunner = 'No hay un Ejecutor de Scripts registrado para archivos de tipo %s';
SErrNoScriptForLang = 'No hay un Ejecutor de Scripts registrado para el lenguaje %s';
SErrUnitNotFound = 'No puedo cargar la unidad %s';
SErrNoRunnableObjects = 'No puedo ejecutarlo';
SErrExternalRun = 'Error ejecutando el programa : %s';
SContinueExecution = '¿ Desea Continuar la ejecución?';
SFilePrefix = 'Archivo : ';
//----------------------------------------------------

SOtherGroupName = 'Otros'; // in Object Inspector
STitleFilterName = 'Nombre del filtro';
STitleFilter = 'Filtro';
SVerbUsesRetriever = 'Usar Recuperador...';
SVerbAssignVerbs = 'Asignar Verbos';
SCapUseObjects = 'Usar Objetos en ';
SCapRunParameters = 'Parametros de Ejecución';

SPageNew = 'Nuevo';
SPageForm = 'Formulario';
SPageUnit = 'Unidad';
SPageReport = 'Informe';
SPageDataModule = 'Módulo de Datos';

SWorkSpace = 'Espacio-de-Trabajo';
SProject = 'Proyecto';

SErrCantSaveObject = 'No puedo guardar el objeto';

SErrDeleteFile = 'No puedo borrar el archivo %S';
SErrRenameFile = 'No puedo renombrar el archivo %s a archivo %s';
SErrCantCreateTemp = 'No puedo crear el archivo temporal';

SStatModified = 'Modificado';
SStatInsert = 'Insertar';
SStatOverwrite = 'Sobreescribir';
SStatReadOnly = 'Solo lectura';

SErrOpenForm = 'Error al abrir el formulario';
SErrDuplicateItem = 'No puedo insertar un elemento duplicado';
SErrReadProps = 'Error leyendo propiedades';

SClipboard = 'Portapapeles';

// OCX
SErrOCXLoadFail = 'Fallo al cargar "%s"';
SErrOCXCantFindProc = '%s procedimiento no encontrado en "%s"';
SErrOCXRegFail = 'Falló la llamada a %s en "%s"';

// ----------------- Filters ------------------------
SOCXFilter = 'ActiveX (*.ocx)|*.ocx';
SAVIFilesFilter = 'Archivos AVI (*.avi)|*.avi';
{$IFDEF CPB3}
SPackagesFilter = 'Paquetes (*.bpl)|*.bpl';
{$ELSE}
SPackagesFilter = 'Paquetes (*.dpl)|*.dpl';
{$ENDIF}
SPictFilter = 'Todos (*.jpg;*.jpeg;*.bmp;*.ico;*.emf;*.wmf)' +
'|*.jpg;*.jpeg;*.bmp;*.ico;*.emf;*.wmf|Archivo de imagen JPEG (*.jpg;*.jpeg)|*.jpg;*.jpeg|' +
'|Mapa de bits (*.bmp)|*.bmp|Iconos (*.ico)|*.ico|' +
'Metaarchivos mejorados (*.emf)|*.emf|Metaarchivos (*.wmf)|*.wmf';
SFormFilter = 'Formulario Delphi|*.dfm';
SColorStyleFilter = 'Esquema de Color|*.RGB';

SExeFilter = 'Archivos Ejecutables|*.EXE;*.DLL;*.DPL;*.BPL|Todos los archivos|*.*';

SExecutableFiles = 'Archivos Ejecutables';

// ---------------- Palette Pages ---------------------
SPalStandard = 'Standard';
SPalAdditional = 'Adicional';
SPalWin32 = 'Win32';
SPalDialogs = 'Dialogos';
SPalSystem = 'Systema';
SPalDataControls = 'Controles de Datos';
SPalDataAccess = 'Acceso a Datos';
SPalMidas = 'Midas';

{
  SPalStandard='Standard';
  SPalAdditional='Aditional';
  SPalWin32='Win32';
  SPalDialogs='Dialogs';
  SPalSystem='System';
  SPalDataControls = 'Data Controls';
  SPalDataAccess = 'Data Access';
  SPalMidas = 'Midas';
}
SPalWin31 = 'Win 3.1';
SPalActiveX = 'ActiveX';
SPalDecisionCube = 'Decision Cube';
SPalQReport = 'QReport';

// ------------------- Form captions ------------------

SCapLines = ' lineas)';
SCapGotoLineNumber = 'Ir al numero de linea';
SCapEnterNewLine = '&Teclee el nuevo numero de linea:';
SCreateOrderCaption = 'Orden de Creación';
STabOrderCaption = 'Orden de Edición';
SCapEditing = 'Editando ';
SCapWindowList = 'Lista de Ventanas';
SCapAddFields = 'Agregar campos';
SCapSelectSource = 'Elegir el DataSource';
SCapScale = 'Escalar';
SCapScalingFactor = 'Factor de E&scala:';
SCapProjectManager = 'Administrador del Proyecto';
SErrDlg = 'Error al leer el Formulario';
SFindText = 'Buscar Texto';
SReplText = 'Reemplazar Texto';
SPstoredEdit = 'Editor de Almacenamiento de Propiedades';
SPackActiveX = 'Paquetes/ActiveX';
SNewItem = 'Nuevo Elemento';
SNewField = 'Nuevo campo';
SFilterEdit = 'Editor de Filtros';
SObjectExplorer = 'Explorador de Objetos';
SStrlEdit = 'Editor de listas alfanumericas';

// ------------------- dcl0.pas ----------------------------

SSaveChanges = 'Guardar cambios a %s?';
SCantUseMore = 'Esta unidad ya usa todas las unidades disponibles';
SUseUnitCaption = 'Usar Unidad';

SEmptyFileName = 'El nombre del archivo no puede estar vacío';
SNotValidIdent = '''%s'' no es un nombre válido.';
SOpenFileExt = 'Unidad Delphi|*.pas|Forma Delphi|*.dfm';
SOnlyOneInstant = 'Solo es posible crear una instancia de TInstantReport';

// ------------------- dcfdes.pas------------------------
SAligntoGrid = 'Alinear a la &cuadrícula';
SBringToFront = 'Traer al &Frente';
SSendToBack = 'Enviar A&trás';
SDesAlign = '&Alinear...';
SDesSize = '&Tamaño...';
SDesScale = '&Escala...';
SDesTabOrder = '&Orden de Edición...';
SDesCreationOrder = 'Orden de &Creación...';
SDesViewAsText = 'View As &Text'; //!!!

// ----------------- dcstring.pas ----------------------

SVerbProperties = 'Propiedades...';
SInvalidTabRack = 'Tab Rack Inválido';
SReadOnlyStream = 'No puedo escribir a un stream de solo lectura';
SErrBlankSearch = 'El texto buscado no puede estar vacío';
SErrEmptySel = 'Se intentó buscar en bloque marcado pero es inválido';
SErrOutsideSel = 'Se intentó buscar desde el cursor en el bloque marcado pero el cursor esta fuera del bloque';
SErrNotFound = 'El Texto buscado ''%s'' no se encontró';
SAskReplace = 'Reemplazar esta ocurrencia de ''%s''?';
SAskSaveFile = '¿ Desea Guardar los cambios de %s ?';

// ----------------------- dcgen.pas ------------------------------

SErrStackEmpty = 'La pila esta vacía';
SErrPackloaderExists = 'El cargador de paquetes ya existía en la aplicación';
SErrUnknRegType = 'Este tipo no es soportado por WriteToRegistry';

// ---------------------- dcpload.pas --------------

SErrWithoutPackages = 'El cargador de paquetes no trabajará si la aplicación fue compilada sin paquetes';
SErrorPackageLoad = 'Error durante el cargado del paquete %S';
SOnlyOnePackageLoader = 'Solo una instancia de TDCPackageLoader puede ser creada';
SUnkPackageHandle = 'El handle del paquete es desconocido';
SPackAlrregist = 'No puedo instalar paquete %s'#13#10'porque el paquete %s tiene el mismo nombre';

// ---------------------- dcl2.pas --------------

SErrFileNotFound = 'Archivo %S no encontrado';

// ---------------------- reswrite.pas --------------

SError = #13#10'Codigo de error : %d';
SErrFileOpen = 'No puedo abrir el archivo para escritura';
SErrMap = 'No puedo mapear archivo';
SErrMapView = 'No puedo ejecutar MapViewOfFile';
SErrEXE = 'Formato de archivo inválido';
SErrNoResources = 'Este archivo no contiene recursos';
SErrResNotFound = 'Recurso no encontrado';

// ---------------------- dcdbreg.pas --------------

SLoadDefault = 'Cargar parametros predefinidos?';
SErrNoAliasOrDriver = 'propiedad AliasName o DriverName deberá ser especificada';
SVerbLoadDefault = 'Cargar parametros pr&edefinidos...';
SVerbExecute = 'E&jecutar';
SVerbColumnsEditor = 'Editor de Co&lumnas...';

// ---------------------- ctrlreg.pas --------------

SVerbEditPropList = '&Editar listado de propiedades...';
SVerbPropOrder = 'Orden de las &Propiedades...';
SVerbInsertObject = 'Insertar Objeto...';
SVerbObjectProperties = 'Propiedades del Objeto...';
SVerbObjectSettings = 'Situación del Objeto...';
SVerbNextFrame = 'Siguie&nte marco';
SVerbPreviousFrame = '&Marco anterior';
SVerbNewPage = 'Nueva pagina';
SVerbNextPage = 'Siguiente pagina';
SVerbPreviousPage = 'Pagina anterior';
SVerbNewButton = 'Nuevo b&otón';
SVerbNewSeparator = 'Nuevo se&parador';

SVerbInputMaskEditor = 'Ed&itor de Máscara de captura...';
SVerbMaskedTextEditor = 'Editor de texto en &Máscara...';
SVerbImageEditor = 'Editor de &imagen..';
SVerbSectionsEditor = 'Editor de Seccio&nes...';
SVerbPanelsEditor = 'Editor de &Paneles...';
SVerbItemsEditor = 'Ed&itor de Elementos...';
SVerbLinesEditor = 'Editor de &Lineas...';
SVerbTabsEditor = 'Edi&tor de Cejas...';
SVerbMenuDesigner = 'Diseñador del Menu...';
SVerbBandsEditor = 'Editor de Ban&das...';
SVerbObjectInspector = '&Inspector de Objetos';

SErrNotImplemented = 'No implementado';

// ---------------------- dcmemo.pas --------------

SLoadColorStyles = 'Leer estilo de colores';
SSaveColorStyles = 'Guardar estilo de colores';
SErrNotRGBFile = 'No es un archivo de estilo de colores';
sScrollLine = '~Line~';
// ---------------------- dcedit.pas --------------

sErrSelfLink = 'No puede ser ligado a si mismo';
sErrEmptyPopupClass = 'No está especificado PopupWindowClass';

// ---------------------- dcmenu.pas --------------

sErrMultipleInstance = 'Solo una instancia de DCMenu puede ser colocada en la forma.';
sErrInfoAlreadySet = 'Información para este elemento de menu ya ha sido definida.';
sErrMainMenuImage = 'Elementos del menu principal no pueden contener imagen';

// ---------------------- dcsplit.pas ---------------

SVerbSetMinSize = 'Definir propiedad MinSize';

// ---------------------- dctree.pas ---------------
SConfirmDelete = 'Borrar elemento(s)';

// ---------------------- dcdbtree.pas ---------------

sDatasetName = '*.cds';
sAddFields = '&Agregar Campos...';
sAddAllColumns = '&Agregar todas las Columnas';
sLoadDefValues = 'Restablecer predefinidos';
sFieldEditor = '&Editor de Campos...';
sParamEditor = 'Editor de &Parametros ...';
serrNameAlredyExists = 'Campo con nombre %s ya existe';
SReplaceColumns = 'Borrar columnas existentes ?';

// ---------------------- dcpascal.pas ---------------

SErrExpectedButFound = '%s esperado pero se encontró %s ';
SErrOrExpected = '%s o  %s esperado';
SErrFunDefined = 'Función %s ya ha sido definida';
SErrunkn_id = 'Identificador desconocido: %s';
SErrunexp_writer = 'Tipo de variable desconocida al escribir el programa';
SErrunit_declared = 'Unidad %s ya ha sido definida';
SErrbad_unit = 'Error de declaración de Unidad';
SErrfun_notfound = 'Función %s no encontrada';
SErrlinker_error = 'Error de Liga';
SErrlabel_already = 'Etiqueta <%s> ya ha sido definida';
SErrdeclpart = 'Error en bloque de declaración';
SErrlab_notdef = 'Etiqueta <%s> no definida';
SErrvar_already = 'Variable <%s> ya ha sido definida';
SErrbad_varblock = 'Error en el bloque de declaración de la variable';
SErrvar_NotDef = 'Variable <%s> no ha sido definida';
SErrmeth_decerr = 'Error en la declaracion del Método';
SErrbad_methparam = 'Error en la declaración de los parametros del Método';
SErrno_props = 'Propiedades no implementadas';
SErronly_class = 'Solo declaraciones de clase permitidas';
SErr_decl = '%s error de declaración';
SErrsynt_err = 'Error de sintaxis en Línea: %d  Carac: %d'#13#10'%s';
SErrbad_idName = 'Nombre incorrecto de identificador <%s>';
SErrbad_id = 'Identificador incorrecto <%s>';
SErrin_funuse = 'Uso de función inválido';
SErrin_procuse = 'Uso de procedure Invalido';
SErrbad_hex = 'Error en declaración de constante Hexadecimal';
SErrcompile_before = 'Compilar antes de ejecutar';
SErrbad_realconst = 'Error en declaración de constante Real';
SErrbad_charconst = 'Error en declaración de constante cadena';
SErrunsup_partype = 'Tipo de parametro no soportado';
SErrno_resvar = 'Resultado de Variable no encontrado para %s';
SErrproc_notfound = 'Procedure %s no encontrado';
SErrpar_notfound = 'Parámetro %S no encontrado';
SErrUnknReaderType = 'Tipo de reader desconocido';
SErrInvalidParams = ' Numero de parametros erroneo';
SErrInvalidType = 'Uno de los parametros no es un tipo de variant válido';
SErrInvalidProperty = 'Propiedad no existe o es de solo-lectura';
SErrInvalidCall = 'Argumentos nombrados no son soportados';
SErrParamNotFound = 'Parametro no encontrado';
SErrTypeMismatch = 'Tipo de parámetro no corresponde';
SErrInvalidInterface = 'Interface desconocida';
SErrParamOmitted = 'Un parametro requerido fue omitido';
SErrUnknown = 'Error desconocido';
SErrInvCode = 'Codigo de operación inválido';

// ---------------------- csDelphi.pas ---------------
SClientDataFilter = 'Client DataSet (*.cds)|*.cds|Todos los archivos (*.*)|*.*';
SSaveToFile = 'Guardar al arch&ivo...';
SLoadFromFile = 'Recuperar &desde archivo...';
SClientDSAssignData = 'Asignar &Datos Locales...';

// ---------------------- dcactnlst.pas ---------------

SDefaultCategory = 'Ninguna';

// ---------------------- AligUnit.pas ---------------

SAlignmentpalette = 'Paleta de Aliniamiento';
SAlignleft = 'Aliniar a orillas izquierdas';
SAlignhor = 'Aliniar centrado horizontal';
SCenterHor = 'Centrar horizontalmente en ventana';
SSpaceeqHor = 'Igual espaciado, horizontalmente';
SAlignright = 'Aliniar a orillas derechas';
SAligntops = 'Aliniar arriba';
SAlignvert = 'Aliniar centrado vertical';
SCentervert = 'Centrar verticalmente en ventana';
SSpaceeqVert = 'Igual espaciado, verticalmente';
SAlignbottom = 'Aliniar al fondo';
SVerbStayOnTop = 'Pe&rmanecer arriba';
SVerbHide = 'E&sconder';

// ---------------------- DAlign.pas ---------------

SAlignment = 'Aliniamiento';
SHorizontal = ' Horizontal';
SVertical = ' Vertical';
SHorizontalAlignment = 'No Cambiar'#13#10'Lados izquierdos'#13#10'Centros'#13#10 +
'Lados derechos'#13#10'Igual Espaciado'#13#10'Centrar en ventana';
SVerticalAlignment = 'No Cambiar'#13#10'Arriba'#13#10'Centros'#13#10 +
'Fondos'#13#10'Igual Espaciado'#13#10'Centrar en ventana';

// ---------------------- DcImgEd.pas ---------------

SAskSeparateBitmaps = 'Dimensiones del mapa de bits para %s son mayores que la dimension del imagelist. Separar en %d mapa de bits separado ?';
SVerbImageListEditor = 'Editor de I&mageList...';
SSelImage = 'Imagen &Seleccionada';
STransColor = 'Color  &Transparente';
SFillColor = '&Llenar con Color';
SOptions = 'Opciones';
SCrop = 'C&ortar';
SStretch = 'Ajusta&r';
SCenter = 'C&entrar';
SApply = 'A&plicar';
SAddImage = '&Agregar';
SDelete = '&Suprimir';
SClear = '&Limpiar';

// ---------------------- DcPalFrm.pas ---------------

SComPal = 'Paleta de Comonentes';

// ---------------------- dcstrled.pas ---------------

SOpen = 'Abrir';
SCodeEdit = 'Editor de &Codigo...';

// ---------------------- dsize.pas ---------------

SSize = 'Tamaño';
SWidth = ' Ancho';
SHeight = ' Altura';
SHorizontalSize = 'No Cambiar'#13#10'Contraer al mínimo'#13#10'Alargar al máximo'#13#10'Ancho:';
SVerticalSize = 'No Cambiar'#13#10'Contrar al minimo'#13#10'Alargar al máximo'#13#10'Altura:';

// ---------------------- glyphed.pas ---------------

SCopy = 'Copiar';
SPaste = 'Pasar';

// ---------------------- inspunit.pas ---------------

SInspectorTabs = 'Propiedades'#13#10'Eventos';
SVerbShowCategory = 'Mostrar Categorías';
SVerbDelphiStyle = 'Estilo Delphi';
SVerbVBStyle = 'Estilo Visual Basic';

// ----------------------MaskPr.pas ---------------

SInputMask = 'Máscara de Captura';
SCharBlank = 'Caracter para &Blancos';
SSaveLiterChar = 'Guardar Caracteres &Literales';
STestInput = '&Probar Captura';
SMask = '&Mascaras...';

// ----------------------MskText.pas ---------------

SInputText = '&Capturar texto';
SEditMask = 'Editar Mascara';

// ----------------------newfield.pas ---------------

SFieldName = '&Nombre';
SFieldType = '&Tipo';

// ----------------------packcfg.pas ---------------

SAddPack = 'Agregar paquete/Registrar ActiveX';
SRemovePack = 'Remover Paquete';
SShowComp = 'Mostrar Componentes';

// ----------------------pstored.pas ---------------

SSelectAll = '&Selecionar Todo';
SUnselectAll = '&Deseleccionar Todo';

// ----------------------replunit.pas ---------------

STextToFind = '&Texto a encontrar:';
SReplaceWith = '&Reemplazar con:';
SCaseSensitive = 'Mayus&ulas/minusculas';
SWholeWord = 'Solo palabras &Completas';
SRegExpr = 'E&xpresiones regulares';
SPropmtRepl = 'C&onfirmar al reemplazar';
SDirection = 'Dirección';
SForward = 'A&delante';
SBackward = 'A&tras';
SScope = 'Ambito';
SGlobal = '&Global';
SSelText = 'Texto &Seleccionado';
SOrigin = 'Origen';
SFromCursor = '&Desde el cursor';
SEntireScope = 'Todo el t&exto';
SReplAll = 'Reempl&azar todo';

sReplace = 'Replace';
sClose = 'Close';

// ----------------------rerdlg.pas ---------------

SErrMess = '%s.  Ignorar el error y continuar?  NOTA: Ignorar el error ' +
'puede causar que componentes sean borrados o se pierdan valores de propiedades.';
SIgnoreAll = 'Ignorar &Todo';

// ----------------------Searunit.pas ---------------

SFind = 'Encontrar';

// ----------------------TreeEd.pas ---------------

SRefresh = 'Renovar';
SLevelUp = 'Un nivel arriba';
SAddItem = 'Agregar elemento';
SAddSubItem = 'Agregar sub-elemento';
SDeleteItem = 'Borrar elemento';
SLargeIcon = '&Iconos grandes';
SSmalIcon = 'Icono&s pequeños';
SListStyle = '&Lista';
SReportStyle = '&Reporte';

//  --------------  added in 2.55  --------------------

// ----------------------MainUnit.pas -------------------------

SFileMenu = '&Archivo';
SFileNewMenu = '&Nuevo...';
SFileNewAppMenu = 'Nueva Aplica&ción';
SFileNewFormMenu = 'Nueva &Forma';
SFileNewDataModuleMenu = 'Nuevo &Modulo de Datos';
SFileOpenMenu = '&Abrir...';
SFileOpenWorkspaceMenu = 'Abrir &Espacio-de-Trabajo...';
SFileSaveWorkspaceMenu = 'Guardar E&spacio-de-Trabajo';
SFileSaveWorkSpaceAsMenu = 'Gua&rdar Espacio-de-Trabajo como...';
SFileSaveAllMenu = 'Guardar &todo';
SFileCloseAllMenu = 'C&errar todo';
SFileUseObjectMenu = '&Usar Objeto...';
SFileAddtoprojectMenu = 'A&gregar al Proyecto...';
SFileRecentFilesMenu = 'Archivos &Recientes';
SFileRecentWorkSpacesMenu = '&Espacios-de-Trabajo recientes';
SFileExitMenu = 'Sa&lir';
SEditMenu = '&Editar';
SEditUndoMenu = '&Deshacer';
SEditRedoMenu = '&Rehacer';
SEditCutMenu = 'Cor&tar';
SEditCopyMenu = '&Copiar';
SEditPasteMenu = '&Pasar';
SEditLockControlsMenu = 'Blo&quear Controles';
SSearchMenu = '&Buscar';
SSearchFindMenu = '&Buscar...';
SFindinFilesMenu = 'Bu&scar en archivos...';
SSearchReplaceMenu = '&Reemplazar...';
SSearchSearchAgainMenu = 'Continuar &busqueda';
SIncrementalSearchMenu = 'Busqueda &Incremental';
SSearchGotoLineMenu = '&Ir a Numero de Línea...';
SViewMenu = '&Ver';
SViewProjectManagerMenu = 'Administrador de &Proyectos';
SViewAlignmentPaletteMenu = 'Paleta de &Aliniamiento';
SViewToggleFormUnitMenu = 'Forma<->Unidad';
SViewWindowListMenu = 'Lista de V&entanas...';
SViewNewEditWindowMenu = 'Nueva Ventana de &Edición';
SViewClipboardHistoryMenu = 'Historia del &Portapapeles';
SViewPackagesMenu = '&Paquetes/ActiveX';
SRunMenu = 'Ejecu&tar';
SRunQuickRunMenu = 'Ejecutar &Externo';
SRunParametersMenu = '&Parametros...';
SRunProgramResetMenu = 'R&einiciar Programa';
SEvaluateModifyMenu = 'E&valuar/Modificar';
SToolsMenuMenu = '&Herramientas';
SToolsOptionsItemMenu = '&Opciones del Ambiente...';
SIDEInspectorMenu = 'Inspector del I&DE';
SHelpMenu = 'Ay&uda';
SHelpContentsMenu = '&Contenido...';
SHelpHomePageMenu = '&Home Page';
SHelpWritetousMenu = '&Escribannos';
SHelpOnlineregMenu = 'Registro &En línea';
SHelpAboutMenu = '&Acerca de...';
SPopupComponentsMenu = 'C&omponentes...';

// ----------------------OptUnit.pas -------------------------

SPreferences = 'Preferencias';
SVbStyle = 'Estilo VB';
SDelphiStyle = 'Estilo Delphi';
SShowCategory = 'Mostrar categorias';
SOInspector = 'Ispector de objetos';
SSmartPopup = 'Muestra inteligente';
SShowHints = 'Show &hints';
SEditAliases = 'Editar aliases';
SFormDesigner = 'Diseñador de la forma';
SGridStepX = 'Increm. cuad. en &X';
SGridStepY = 'Increm. cuad. en &Y';
SDisplayGrid = 'Desplegar &cuadricula';
SSnapToGrid = 'Aj&ustar a la cuadricula';
SShowCaptions = '&Mostrar etiquetas de componentes';
SDsgnHints = 'Designer &hints';
SEditor = 'Editor';
STabStops = 'Paradas del &Tabulador:';
SBlockIndent = 'I&ndentar bloques:';
SKeyMappings = 'Mapeo-de-teclas';
SEditorOptions = 'Opciones del Editor';
SAutoIndentMode = 'Modo de &Auto indentación';
SSmartTab = 'Tabs &inteligentes';
SBackUnindents = 'No indentar en retroceso';
SShowLineNumbers = 'Mostrar numeros de &linea';
SGroupUndo = 'A&grupar al deshacer';
SCursorBeyondEof = 'Cursor mas allá de &EOF';
SKeepTrailingBlanks = '&Keep trailing blanks';
SPersistentBlocks = 'Bloques &persistentes';
SOverwriteBlocks = '&Sobreescribir bloques';
SDblClickLine = '&Doble click en la línea';
SFindTextAtCursor = 'Encontrar te&xto en el cursor';
SCutCopyEnabled = '&Forzar activado de cortar y copiar';
SSyntaxHighlighting = 'Usar resaltar &sintaxis';

SCursorByondEol = '&Cursor excede EOL';
SSelectionByondEol = '&Selección excede EOL';
sDisplaySpecialChars = 'Display Special Chars';
SOverCaretBlock = 'S&obreescribir bloques';
SDisableDrag = 'Desactivar a&rrastrar';

SDisplay = 'Pantalla';
SEditFont = '&Fuente del Editor:';
SUseMonoFont = '&Use mono font';
SOptionSize = '&Tamaño:';
SEditMargin = 'Margen del editor :';
SColor = '&Color:';
SColor2 = 'C&olor:';
SStyle = '&Estilo:';
SStyle2 = 'E&stilo:';
SOptionWidth = '&Ancho:';
SOptionWidth2 = 'A&ncho:';
SPosition = '&Posicion:';
SVisible = '&Visible';
SVisible2 = 'V&isible';
SEditGutter = 'Cuneta del Editor:';
SEditorColor = 'Color del E&ditor:';
SColors = 'Colores';
SElements = '&Elemento:';
SColorSpeedSetting = 'Color S&peedSetting:';
STextAttrs = ' Text attributes: ';
SBackColor = 'Color del &Fondo:';
SForeColor = 'Color del F&rente:';
SUseReadOnlyColor = 'Use &Read-Only Color';
SReadOnlyColor = 'Read-&Only Color:';
SUseSpecSymbs = 'Draw &Special Symbols';
SEOF = 'EOF:';
SEOL = 'EOL:';
SSpace = 'Space:';
STab = 'Tab:';

SBoldFont = '&Negritas';
SItalicFont = '&Italicas';
SUnderLineFont = '&Subrayadas';

//------------editunit.pas--------------------------

SOpenFileatCursor = 'Insertar &archivo en el Cursor';
SBrowseSymbolatCursor = '&Examinar Símbolo en el Cursor';
STopicSearch = 'Bu&scar Tópico';
SToggleBreakpoint = 'Activa/desactiva Punto de ruptura';
SRuntoCursor = 'Ejec&utar hasta el Cursor';
SAddWatchatCursor = '&Agregar variable en el Cursor...';
SViewasForm = '&Ver como Formulario';
SReadOnly = 'S&olo-lectura';
SClosePage = '&Cerrar página';
SMessageView = 'Ver &Mensaje';

SSelectDirectory = 'Seleccionar Directorio';

//------------formfill.pas--------------------------

SErrFillTypeStarted = 'Ya fué iniciado el autorelleno';

//----------------diffmake.pas------------------------

SErrCRC = 'Error de CRC';
SErrSmallBuffer = 'El tamaño del buffer deberá ser de al menos de 4 bytes';

//---------dcmenu.pas--------------------------------------
sErrNotAForm = 'DCMenu solo puede ser colocado dentro de una forma';

//---------dcpascal.pas--------------------------------------

SErrMisplacedBreak = 'Un Break está fuera del ciclo';
SErrMisplacedContinue = 'Un Continue está fuera del ciclo';

//---------dcstdctl.pas--------------------------------------

SErrCircularReference = 'Referencia circular';

//---------dtreeed.pas--------------------------------------

SNewNode = 'Nuevo Nodo';

{------------------------------------------------------------}

SShowLineNumbersOnGutter = '&Muestra numeros de linea en cuneta';

SUseDefaults = ' Usar valor por defecto para: ';
SForeground = '&Frente';
SBackground = 'Fo&ndo';

SProperties = 'Propiedades';
SOkButton = 'Acepta';
SCancelButton = 'Cancela';
SHelpButton = 'Ay&uda';
//=================== UNTRANSLATED SECTION ===================
{------------ This section will be translated ---------------}
sDCCloseButton = 'Close';
sDCResumeButton = 'Resume';
SSaveButton = 'Save';
SDeleteButton = 'Delete';
//================= END UNTRANSLATED SECTION =================

SInspectOptions = 'Inspector';
SDesignerOptions = 'Diseñador';

SFileExportToMenu = '&Exportar A';
SFilePrintMenu = 'Im&primir...';

//--------------------- Dialog titles --------------

SExportToTitle = 'Exportar A';
SSaveAsTitle = 'Guardar Como';
SOpenTitle = 'Abrir';

//------------- Info Tree constants -------------------------

SErrReferencedObject = 'El objecto tiene referencias de otros objetos';

SErrEmptyLink = '%s: La liga no esta especificada';
SIUnknownNotSupported = 'IUnknown no es soportado';
SIDCRowSetNotSupported = 'IDCRowSet no es soportado';
SErrActiveObject = 'El objeto está activo. Por favor cierrelo';
SErrNonActiveInfoSet = 'InfoSet no está activo. Por favor abralo';
SErrUnsupportedDataType = 'El campo "%s" tiene tipo de datos no soportados';
SErrSetInfoSet = 'Por favor defina propiedad InfoSet';
SErrFieldReadOnly = 'El campo "%s" es de solo lectura';
SErrFieldDestroyed = 'El campo "%s" está destruido';
SErrHandlerAlreadyExists = 'El Handler ya existe';
SErrHandlerNotExists = 'El Handler no existe';
SErrObjectIsNull = 'El objeto es NULL';
SIDCMasterInfoSetNotSupported = 'IDCMasterInfoSet no es soportado';
SErrInsert = 'No puedo insertar nodo';
SErrChangesNotSupported = 'Infoset no soporta modificaciones';

//ReliInfoSet messages
SErrFieldNotFound = 'Los campos "%s" no fueron encontrados.';

SErrSetReliItem = 'Por favor define propiedad %s';
SErrCMastAndDetDifferent = 'Numeros deampos Maestros y de Detalles no corresponden';
SErrRelFieldNotFound = 'Los campos "%s" no fueron encontrados.';
SErrEmptyDisplayField = 'DisplayName está vacío';
SErrIncompatibleDataType = 'El tipo de datos de maestra "%s" y detalle "%s" son incompatibles';

SErrSetReliItemIndex = 'Por favor defina propiedad %s. Error en elemento con indice %d';
SErrCMastAndDetDifferentIndex = 'El número de los campos de Detalles y Maestrono corresponden. Error en elemento con índice %d';
SErrRelFieldNotFoundIndex = 'Campos "%s" no fueron encontrados. Error en elemento con indice %d';
SErrEmptyDisplayFieldIndex = 'displayName está vacío. Error en elemento con indice %d';
SErrIncompatibleDataTypeIndex = 'El tipo de datos de maestra "%s" y detalle "%s" son incompatibles. Error en elemento con indice %d';

SErrInvalidFilter = 'La expresión del filtro fue formada incorrectamente';
SErrInvalidFieldType = 'Tipo de campo invalido';
SErrSetDataSet = '%s: Por favor defina propiedad DataSet';
SErrSetRootDataSet = '%s: Por favor defina propiedad RootDataSet';
SErrNotInfoSetDataSet = 'El valor debe ser TDataSet o InfoSet';

//InfoDB constants
SErrUniqueFieldAlreadyRegistered = 'Campo unico ya fue registrado';
SErrUniqueFieldIsNotRegistered = 'El campo único para este DataSet no está registrado';
SErrInvalidBookmark = 'Bookmark invalido';

//Memo print messages
SFileNameUnknown = '<Desconocido>';
SFileSelectedBlock = '<Bloque seleccionado>';
SPrintingPage = 'Imprimiendo pagina %d de %s';
SPageCaption = 'Pagina %d/%d';
SMultiDot = ' ... ';
SPrintingOnPrinter = 'Imprimiendo en impresora %s';

//Print progress messages
SPrintStatus = 'Estado de la impresión';
SSearchPrinters = 'Investigando impresoras ...';
SPrintProgress = 'Imprimiendo paginas:    calculando ...';

//Print Dialog messages
SPrintFormCaption = 'Imprimir';
SPrintFormCaptionSelection = 'Imprimir Selección';
SPrintDestCaption = 'Archivo A Imprimir:';
SPrintSelectedBlock = 'Im&primir bloque seleccionado';
SOptionsCaption = 'Opciones:';
SSetupButton = 'Co&nfigurar...';
SHeaderPage = '&Numero de Encabezado/página';
SFooterPage = '&Footer';
SLineNumber = 'Numeros de &línea';
SSyntaxPrint = 'Imprimir &sintaxis';
SUseColor = 'Usar &color';
SShowPrintProgress = 'Mostrar avance de im&presión';
SWrapLines = '&Fluir lineas';
SLeftMargin = '&Margen izquierdo:';

SErrScriptLanguageNotSpecified = 'Lenguage Scripting no está especificado';

//TSyntaxScheme
SCantReadSSchemeFrom = 'Can''t read syntax scheme from ';
SFromFile = 'file';
SFromStream = 'stream';
SSchemeEditor = 'Scheme Editor...'; //!
SFirstCharAccent = ''; //in most cases this const should be empty
SOtherCharAccent = ''; //in most cases this const should be empty

//TSyntaxScheme Editor section
SSSETitle = 'Editor TSyntaxScheme';
SSchemeName = '&Nombre de Esquema:';
SBlocks = '&Bloques';
SExtensions = '&Extensions';
SLoad = 'Leer';
SSave = 'Guardar';
SLoad1 = '&Leer';
SSave1 = '&Guardar';
SSaveAs = 'Guardar como';
SClear0 = 'Limpiar';
SApply0 = 'Aplicar';
SBlkDelimiters = '&Delimitadores de bloque:';
SBlkOptions = 'Opciones de Bloque:';
SCaseSens = 'Mayús&culas/minúsculas';
SUseMeta = 'Usar &MetaSymbol';
SMetaEscape = 'para &Escapes';
SMetaWrapLines = 'para &Fluir lineas largas';
SStyleText = '&Text simple:';
SUseSymbols = 'Resaltar S&imbolos';
SPageCommon = 'Common';
SPageComments = 'Comments';
SPageFullLine = 'FullLine';
SPageStrings = 'Strings';
SPageNumbers = 'Numbers';
SPageIdents = 'Identifiers';
SPageKeywords = 'Keywords';
SPagePopups = 'Popups';
SAdd = 'Aggregar';
SRemove = 'Remover';
SEdit = 'Editar';
SAdd1 = '&Agregar';
SRemove1 = '&Remover';
SEdit1 = '&Editar';
SAdd2 = 'A&gregar';
SRemove2 = 'Remo&ver';
SEdit2 = 'Edi&tar';
SStyleButton = 'Estilo...';
SUseComments = 'Resaltar &Comentarios';
SUseCommentsSL = 'Comentarios Línea-senc&illa';
SUseCommentsML = 'Comentarios Línea-&multiple';
SUseCommentsFL = 'Comentarios Línea-c&ompleta';
SUseDirectives = 'Resaltar &Directivas';
SUseStrings = 'Resaltar Cade&nas';
SUseStringsSL = 'Cadenas Línea-senc&illa';
SUseStringsML = 'Cadenas Línea-&multiple';
SUseNumbers = 'Resaltar N&umeros';
SIntNum = 'En&tero:';
SFloatNum = 'Flo&tante:';
SHexNum = '&Hexadecimal:';
SPSNumbers = ' Especial: ';
SWithPrefix = 'con &prefijo';
SWithSuffix = 'con su&fijo';
SWithPS = 'con pref&ijo y sufijo';
SWithPrefixes = 'con prefi&jos';
SWithSuffixes = 'con sufi&jos';
SWithPSs = 'con prefi&es y sufijos';
SMultiSuffixes = 'multiple sufijos permiti&dos';
SPSComposition = 'usa &composición de P y S';
SUseIdentifiers = 'Resaltar I&dentificadores';
SCaptionFirstChar = 'First Symbol CharSet:'; //!
SCaptionOtherChar = 'Other Symbols CharSet:'; //!
SCaptionCharSet = '&CharSet:';
SUseKeywords = 'Resaltar &Palabras reservadas:';
SKWSets = ' Conjuntos: ';
SCurKWSets = ' Actual Conjunto de Palabras reservadas: ';
SFontName = '&Nombre de Fuente:';
SFontSize = 'Tamañ&o de Fuente:';
SFontColor = '&Color de Fuente:';
SFontStyles = 'Estilos de Fuente:';
SBackColor1 = '&Color de Fondo:';
SBold = '&Negritas';
SItalic = '&Italicas';
SUnderline = '&Subrayadas';
SStrikeout = '&Tachadas';
STextStyle = 'Ñòèë&ü òåêñòà:';
SUseDefFont = 'Usar fuente por omisión';
SUseDefBack = 'Usar fondo por omisión';
SArePartOfBlock = 'Son &parte del bloque';
SSelectBlock = '&Seleccionar bloque:';
SFilterScheme = 'Archivos esquema sintaxis (*.sch)|*.sch|Todos los archivos (*.*)|*.*';
SFilterKeywords = 'Archivos Texto (*.txt)|*.txt|Todos los archivos (*.*)|*.*';
SCaptionSet = 'Conjunto:';
SCaptionKeyword = '&Palabra reservada:';
SCaptionDelimiter = '&Delimitador:';
SCaptionLeftDlmtr = 'Delimitador &Izquierdo:';
SCaptionRightDlmtr = 'Delimitador &Derecho:';
SCaptionPrefix = 'Prefijo:';
SCaptionSuffix = 'Sufijo:';
SCaptionBlock = '&Bloque:';
SCaptionParent = '&Parent:';
SCaptionExt = 'E&xtension:';
SQueryRemoveBlock = 'Realmente quiere remover sintaxis del bloque';
SQueryRemoveKWSet = 'Realmente quiere remover palabras reservadas del conjunto';
SAnd = ' y ';

//=================== UNTRANSLATED SECTION ===================
{------------ This section will be translated ---------------}

//DC Menu Designer
sDCMenuDesigner = 'Menu Designer...';
sDCMenuValue = '(Menu)';
sDCInsertMenuItemCaption = '&Insert';
sDCDeleteMenuItemCaption = '&Delete';
sDCCreateSubMenuMenuItemCaption = '&Create Submenu';
sDCSelectMenuItemCaption = 'Se&lect Menu...';
sDCSelectMenuFormCaption = 'Select Menu';

//InspUnit OI Descriptions
SDescrName = 'Name=Returns/sets the name used in code to identify an object.';
SDescrCaption = 'Caption=Returns/sets the text displayed in an objects''s title bar or below an object''s icon.';
SDescrBorderStyle = 'BorderStyle=Returns/sets the border style for an object.';
SDescrCtl3d = 'Ctl3d=Returns/sets whether or not an object is painted at run time with 3-D effects.';
SDescrKeyPreview = 'KeyPreview=Returns/sets whether keyboard events for an object are invoked before keyboard events for controls on that object.';
SDescrHeight = 'Height=Returns/sets the height of an object.';
SDescrLeft = 'Left=Returns/sets the distance between the internal left edge of an object and the left edge of its container.';
SDescrTop = 'Top=Returns/sets the distance between the internal top edge of an object and the top edge of its container.';
SDescrWidth = 'Width=Returns/sets the width of an object.';
SDescrWindowState = 'WindowState=Returns/sets the visual state of a form window at run time.';
SDescrVisible = 'Visible=Returns/sets a value that determines whether an object is visible or hidden.';
SDescrPosition = 'Position=Returns or sets a value specifying the position of a Form when it first appears.';
SDescrCursor = 'Cursor=Returns/sets the type of mouse pointer displayed when over part of an object.';
SDescrIcon = 'Icon=Returns the icon displayed when a form is minimized at run time.';
SDescrHelpContext = 'HelpContext=Specifies the default Help file context ID for an object.';
SDescrEnabled = 'Enabled=Returns/sets a value that determines whether an object can respond to user-generated events.';
SDescrDragMode = 'DragMode=Returns/sets a value that determines whether manual or automatic drag mode is used.';
SDescrPasswordChar = 'PasswordChar=Returns/sets a value that determines whether characters typed by a user or placeholder characters are displayed in a control.';
SDescrScrollBars = 'ScrollBars=Returns/sets a value indicating whether an object has vertical or horizontal scroll bars.';
SDescrHint = 'Hint=Returns/sets the text displayed when the mouse is paused over the control.';
SDescrDataField = 'DataField=Returns/sets a value that binds a control to a field in the current record.';
SDescrDataSource = 'DataSource=Sets a value that specifies the Data control through which the current control is bound to a database.';
SDescrAutoSize = 'AutoSize=Determines whether a control is automatically resized to display its entire contents.';
SDescrInterval = 'Interval=Returns/sets the number of milliseconds between calls to a Timer control''s OnTimer event.';
SDescrTag = 'Tag=Stores any extra data needed for your program.';
SDescrTabStop = 'TabStop=Returns/sets a value indicating whether a user can use the TAB key to give the focus to an object.';
SDescrTabIndex = 'TabIndex=Returns/sets the tab order of an object within its parent control.';
SDescrShape = 'Shape=Returns/sets a value indicating the appearance of a control.';
SDescrCancel = 'Cancel=Indicates whether a command button is the Cancel button on a form.';
SDescrDefault = 'Default=Determines which button control is the default command button on a form.';
SDescrColor = 'Color=Returns/sets the background color of the component.';
SDescrFont = 'Font=Returns/sets the font characteristics of the component, including typeface, size, attributes and color.';
SDescrParentFont = 'ParentFont=Determines where a control looks for its font information.';
SDescrShowHint = 'ShowHint=Determines if the control should display a hint when the mouse pointer rests momentarily on it.';
SDescrPopupMenu = 'PopupMenu=Identifies the pop-up menu associated with the control.';
SDescrActiveControl = 'ActiveControl=ActiveControl is the control that has focus on the form.';
SDescrScaled = 'Scaled=Specifies whether the form is sized according to the value of the PixelsPerInch property or not.';
SDescrPrintScale = 'PrintScale=Value that represents the proportions of a printed form.';
SDescrAutoScroll = 'AutoScroll=Specifies whether scroll bars appear automatically on the scrolling windowed control or not.';
SDescrBorderIcons = 'BorderIcons=Set of values that specify which icons appear on the title bar of the form.';
SDescrClientHeight = 'ClientHeight=Height of the control''s client area in pixels.';
SDescrClientWidth = 'ClientWidth=Width of the control''s client area in pixels.';
SDescrWindowMenu = 'WindowMenu=Window menu for an MDI parent form.';
SDescrFormStyle = 'FormStyle=Set of values that represent the form''s style.';
SDescrHelpFile = 'HelpFile=Specifies the name of the file the application uses to display Help.';
SDescrMenu = 'Menu=Form''s main menu.';
SDescrObjectMenuItem = 'ObjectMenuItem=OLE object menu item that reacts to selections of OLE objects.';
SDescrPixelsPerInch = 'PixelsPerInch=Value that represents the proportion of the font on the system on which the form was designed.';
SDescrHorzScrollBar = 'HorzScrollBar=An object that encapsulates the horizontal scroll bar for the scrolling windowed control.';
SDescrVertScrollBar = 'VertScrollBar=An object that encapsulates the vertical scroll bar for the scrolling windowed control.';
SDescrFontCharSet = 'Font.CharSet=Specifies the character set of the font.';
SDescrFontColor = 'Font.Color=Specifies the color of the text.';
SDescrFontHeight = 'Font.Height=Specifies the height of the font.';
SDescrFontName = 'Font.Name=Identifies the typeface of the font.';
SDescrFontPitch = 'Font.Pitch=Specifies whether the characters in the font all have the same width.';
SDescrFontSize = 'Font.Size=Size is the height of the font in points.';
SDescrFontStyle = 'Font.Style=Determines whether the font is normal, italic, underlined, bold, and so on.';
SDescrOnActivate = 'OnActivate=Occurs when the object becomes active.';
SDescrOnClick = 'OnClick=Occurs when the user clicks the control.';
SDescrOnClose = 'OnClose=Occurs when the form closes.';
SDescrOnCloseQuery = 'OnCloseQuery=Occurs when the Close method is called or when the user closes from using system menu.';
SDescrOnCreate = 'OnCreate=Occurs when the form is created.';
SDescrOnDblClick = 'OnDblClick=Occurs when the user double-clicks mouse button when the mouse is over the control.';
SDescrOnDestroy = 'OnDestroy=Occurs when the form is destroyed.';
SDescrOnDeactivate = 'OnDeactivate=Occurs when the form loses focus.';
SDescrOnDragDrop = 'OnDragDrop=Occurs when the user drops an object being dragged.';
SDescrOnDragOver = 'OnDragOver=Occurs when the user drags an object over a control.';
SDescrOnHide = 'OnHide=Occurs when the form is going to be hidden.';
SDescrOnHelp = 'OnHelp=Occurs when the form receives a request for help.';
SDescrOnKeyDown = 'OnKeyDown=Occurs when a user presses any key while the control has focus.';
SDescrOnKeyPress = 'OnKeyPress=Occurs when a user presses a single character key.';
SDescrOnKeyUp = 'OnKeyUp=Occurs when the user releases a key that has been pressed.';
SDescrOnMouseDown = 'OnMouseDown=Occurs when the user presses a mouse button with the mouse pointer over a control.';
SDescrOnMouseMove = 'OnMouseMove=Occurs when the user moves the mouse pointer while the mouse pointer is over a control.';
SDescrOnMouseUp = 'OnMouseUp=Occurs when the user releases a mouse button that was pressed with the mouse pointer over a component.';
SDescrOnPaint = 'OnPaint=Occurs when the object is redrawn.';
SDescrOnResize = 'OnResize=Occurs when the object is resized.';
SDescrOnShow = 'OnShow=Occurs when the object is shown.';

// Component Palette
sDCCannotSaveToRegistry = 'Error occurs while saving palette to registry.';
sDCIndexOutOfBound      = 'Index out of bounds';

sLessButton = '&Less';
sMoreButton = '&More';
sReplacements = '%d replacements have been made';
sFindAndRepl = 'Find and Replace';
sGoTo = 'Go To';
sLine = 'Line';
sBookMark = 'BookMark';
sErrBookmarNotFound = 'Bookmark %d not found';


//dcRenPropPageUnit
SDCRenPropPageFormCaption = 'Rename page';
SDCAddPropPageFormCaption = 'Add page';
SDCPageNameCaption = 'Page name:';
SDCDublicatePageName = 'The name '#39'%s'#39' is already in use.';

//dcPalettePropUnit
SDCPalettePropFormCaption = 'Palette';
SDCPaletteSheetCaption = 'Palette';
SDCAddBtnCaption = '&Add...';
SDCDeleteBtnCaption = '&Delete';
SDCRenameBtnCaption = '&Rename...';
SDCMoveUpBtnCaption = 'Move &Up';
SDCMoveDownBtnCaption = 'Move D&own';
SDCPagesLabelCaption = 'Pages:';
SDCComponentLabelCaption = 'Components:';
SDCAllCompItemCaption = '[All]';
SDCDefaultPagesBtnCaption = 'De&fault pages';

SDCNameColCaption = 'Name';
SDCPackageColCaption = 'Package';
SDCPageColCaption = 'Page';

SDCFullPageError = 'A page must be empty before it can be deleted.';
sDCHiddenComponent = '[Hidden]';
sDCShowBtnCaption = '&Show';
sDCHideBtnCaption = '&Hide';

const
sWithClause = 'with';
sWithOutClause = 'without';


//Object Inspector Aliases
const
  DefaultInspectorAliases = (
    '[Appearance]'#13#10+
    'Color'#13#10+
    'Caption'#13#10+
    'Cursor'#13#10+
    'Alignment'#13#10+
    'ParentColor'#13#10+
    'Transparent'#13#10+
    'WordWrap'#13#10+
    'Flat'#13#10+
    'Glyph'#13#10+
    'Ctl3d'#13#10+
    ''#13#10+
    '[Behavior]'#13#10+
    'OnEditButtonClick'#13#10+
    'OnEnter'#13#10+
    'OnExit'#13#10+
    'TabOrder'#13#10+
    'TabStop'#13#10+
    'DragCursor'#13#10+
    'DragMode'#13#10+
    'Cancel'#13#10+
    'Default'#13#10+
    'Enabled'#13#10+
    'Visible'#13#10+
    'GroupIndex'#13#10+
    'ImeMode'#13#10+
    'ImeName'#13#10+
    ''#13#10+
    '[List]'#13#10+
    'IntegralHeight'#13#10+
    'ItemHeight'#13#10+
    'Items'#13#10+
    'MultiSelect'#13#10+
    ''#13#10+
    '[Font]'#13#10+
    'Font'#13#10+
    'ParentFont'#13#10+
    ''#13#10+
    '[Misc]'#13#10+
    'Name'#13#10+
    'PopupMenu'#13#10+
    'HelpContext'#13#10+
    'Tag'#13#10+
    'FocusControl'#13#10+
    ''#13#10+
    '[Hint]'#13#10+
    'ParentShowHint'#13#10+
    'ShowHint'#13#10+
    'Hint'#13#10+
    ''#13#10+
    '[Position]'#13#10+
    'Height'#13#10+
    'Top'#13#10+
    'Left'#13#10+
    'Width'#13#10+
    'Autosize'#13#10+
    'Align'#13#10+
    ''#13#10+
    '[Data]'#13#10+
    'DataSource'#13#10+
    'DataSet'#13#10+
    'DataField'#13#10+
    ''#13#10+
    '[Keyboard]'#13#10+
    'OnKeyDown'#13#10+
    'OnKeyPress'#13#10+
    'OnKeyUp'#13#10+
    ''#13#10+
    '[Mouse]'#13#10+
    'OnClick'#13#10+
    'OnDblClick'#13#10+
    'OnMouseDown'#13#10+
    'OnMouseMove'#13#10+
    'OnMouseUp'#13#10+
    ''#13#10+
    '[DragDrop]'#13#10+
    'OnDragDrop'#13#10+
    'OnDragOver'#13#10+
    'OnEndDrag'#13#10+
    'OnStartDrag'
    );


sDCErrorPrefix = '[Error]';

sDCNewMenuCaption    = '&New';
sDCOpenMenuCaption   = '&Open';
sDCSaveMenuCaption   = '&Save';
sDCSaveAsMenuCaption = 'Save &As...';
sDCExitMenuCaption   = '&Exit';

sDCNewActionHint    = 'New';
sDCOpenActionHint   = 'Open';
sDCSaveActionHint   = 'Save';
sDCSaveAsActionHint = 'Save as...';
sDCExitActionHint   = 'Exit';

sDCProcessStatusLabelCaption = 'Process status:';

sDCProcedures = 'Procedures';
sDCClasses    = 'Classes';
sDCTypes      = 'Types';
sDCVariales   = 'Variables';
sDCConstants  = 'Constants';
sDCProperties = 'Properties';
sDCMethods    = 'Methods';

sDCNoFieldsAreAvailable = 'No fields are available.';

sDCSourceLabel      = 'Available fields:';
sDCDestinationLabel = 'Participating fields:';

sDCComponentsListFormCaption = 'Components';
sDCComponentsListPanelCaption = '&Installed components';

sDCActiveXEditorCaption = 'ActiveXs';
sDCActiveXPanelCaption = 'Design &ActiveXs';
sDCComponentsBtnCaption = '&Components';

sDCPackagesEditorCaption = 'Packages';
sDCPackagesPanelCaption = 'Design &packages';
sDCRemoveBtnCaption = '&Remove';
sDCEditBtnCaption = '&Edit';
sUseTabChar = '&Use tab character';

//TreeNodesEditor
STrEdCaption = '.Items Editor';
SNodeTypeNone = 'None';
SNodeTypeCheckBox = 'CheckBox';
SNodeTypeRadioButton = 'RadioButton';
SStateUnchecked = 'Unchecked';
SStateChecked = 'Checked';
SStateGrayed = 'Grayed';
STrEdNewItem = 'New Ite&m';
STrEdNewSubItem = 'New Su&bItem';
STrEdClear = 'Clea&r';
STrEdMoveUp = 'Move &Up';
STrEdMoveDown = 'Move Do&wn';
STrEdDragNDropAsChild = 'Drag''n''Drop as child';
STrEdItemProperties = 'Item Properties';
STrEdText = 'Te&xt:';
STrEdIndexes = 'Indexes:';
STrEdImage = '&Image:';
STrEdSelected = 'S&elected:';
STrEdStateIndex = 'S&tate:';
STrEdOverlay = 'O&verlay:';
STrEdParentFont = '&Parent Font';
STrEdFont = '&Font:';
STrEdParentColor = 'Parent C&olor';
STrEdColor = '&Color:';
STrEdType = 'T&ype:';
STrEdAllowGrayed = 'Allow &Grayed';
STrEdState = 'St&ate:';
STrEdReadOnly = 'Read-O&nly';

//================= END UNTRANSLATED SECTION =================

SCannotCreateName = 'Cannot create a method for an unnamed component';
